src/objects/Audit__c.object
<CustomObject>
    <label>Audit</label>
    <nameField>
        <label>Audit Element Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Audit_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Audit__c</fullName>
        <label>Audit</label>
        <referenceTo>Audit__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Audit_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Audits</relationshipLabel>
        <relationshipName>Audit_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Audit/Objective Association</label>
    <nameField>
        <displayFormat>AOA-{0000}</displayFormat>
        <label>Audit/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Governance</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Governance__c.Parent_or_Subsidiary_Governance__c</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Subsidiary Governance</relationshipLabel>
        <relationshipName>Governance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance_Objectives_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Objectives Association</label>
    <nameField>
        <displayFormat>GO{00000}</displayFormat>
        <label>Governance Objectives Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Objectives Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objective_Vendor_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objective__c</fullName>
        <label>Objective</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Objective/Vendor Associations</relationshipLabel>
        <relationshipName>Associated_Vendor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.  Account Record type must be Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Objective/Vendor Associations</relationshipLabel>
        <relationshipName>Objective_Vendor_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Objective/Vendor Association</label>
    <nameField>
        <displayFormat>OVA{00000}</displayFormat>
        <label>Objective/Vendor Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objective/Vendor Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Processes</relationshipLabel>
        <relationshipName>Process_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Objective_Process_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process/Objective  Association</label>
    <nameField>
        <displayFormat>OP{00000}</displayFormat>
        <label>Process/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Objective Association</label>
    <nameField>
        <displayFormat>POA-{000000}</displayFormat>
        <label>Product/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Objective Association</label>
    <nameField>
        <displayFormat>PO{00000}</displayFormat>
        <label>Project/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Risk_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Objective Association</label>
    <nameField>
        <displayFormat>RO{00000}</displayFormat>
        <label>Risk/Objective Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ObjectiveAssociationJSONToolkit.cls
global class ObjectiveAssociationJSONToolkit {
    webservice static String toJSON(String objectiveID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        
        categoryNames.add('Audits');
        categoryNames.add('Governances');
        //categoryNames.add('Internal Audit Subtasks');
        categoryNames.add('Vendors');
        categoryNames.add('Processes');
        categoryNames.add('Products');
        categoryNames.add('Projects');
        categoryNames.add('Risks');

        List<Audit_Objective_Association__c> audits = [SELECT Objectives__r.Id, Objectives__r.Name, Audit__r.Id, Audit__r.Name from Audit_Objective_Association__c where Objectives__r.Id =:objectiveID];
        List<Governance_Objectives_Association__c> governances = [SELECT Objectives__r.Id, Objectives__r.Name, Governance__r.Id, Governance__r.Name from Governance_Objectives_Association__c where Objectives__r.Id =:objectiveID];
        //List<Internal_Audit_Objective_Association__c> internalauditsubtasks = [SELECT Objectives__r.Id, Objectives__r.Name, Internal_Audit_Subtask__r.Id, Internal_Audit_Subtask__r.Name from Internal_Audit_Objective_Association__c where Objectives__r.Id =:objectiveID];
        List<Objective_Vendor_Association__c> vendors = [SELECT Objective__r.Id, Objective__r.Name, Vendor__r.Id, Vendor__r.Name from Objective_Vendor_Association__c where Objective__r.Id =:objectiveID];
        List<Process_Objective_Association__c> processes = [SELECT Objectives__r.Id, Objectives__r.Name, Process__r.Id, Process__r.Name from Process_Objective_Association__c where Objectives__r.Id =:objectiveID];
        List<Product_Objective_Association__c> products = [SELECT Objectives__r.Id, Objectives__r.Name, Product__r.Id, Product__r.Name from Product_Objective_Association__c where Objectives__r.Id =:objectiveID];
        List<Project_Objective_Association__c> projects = [SELECT Objectives__r.Id, Objectives__r.Name, Project__r.Id, Project__r.Name from Project_Objective_Association__c where Objectives__r.Id =:objectiveID];
        List<Risk_Objective_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Objectives__r.Id, Objectives__r.Name from Risk_Objective_Association__c where Objectives__r.Id =:objectiveID];


        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'OBJECTIVE');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                           
                           if (categoryName == 'Audits')
                            {
                                for (Audit_Objective_Association__c audit : audits)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', audit.Audit__r.Name);
                                        generator.writeStringField('objectID', audit.Audit__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Governances')
                            {
                                for (Governance_Objectives_Association__c governance : governances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', governance.Governance__r.Name);
                                        generator.writeStringField('objectID', governance.Governance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            /*
                            else if (categoryName == 'Internal Audit Subtasks')
                            {
                                for (Internal_Audit_Objective_Association__c internalauditsubtask : internalauditsubtasks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', internalauditsubtask.Internal_Audit_Subtask__r.Name);
                                        generator.writeStringField('objectID', internalauditsubtask.Internal_Audit_Subtask__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            */
                            else if (categoryName == 'Vendors')
                            {
                                for (Objective_Vendor_Association__c vendor : vendors)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', vendor.Vendor__r.Name);
                                        generator.writeStringField('objectID', vendor.Vendor__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Processes')
                            {
                                for (Process_Objective_Association__c process : processes)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', process.Process__r.Name);
                                        generator.writeStringField('objectID', process.Process__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Products')
                            {
                                for (Product_Objective_Association__c product : products)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', product.Product__r.Name);
                                        generator.writeStringField('objectID', product.Product__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Projects')
                            {
                                for (Project_Objective_Association__c project : projects)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', project.Project__r.Name);
                                        generator.writeStringField('objectID', project.Project__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Risks')
                            {
                                for (Risk_Objective_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                         generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}