src/objects/Audit__c.object
<CustomObject>
    <fields>
        <fullName>Audit_Item_Description__c</fullName>
        <description>Short name describing Audit description</description>
        <inlineHelpText>Enter a brief description of the audit overview</inlineHelpText>
        <label>Audit Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Audit</label>
    <nameField>
        <label>Audit Element Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Audit_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Audit__c</fullName>
        <label>Audit</label>
        <referenceTo>Audit__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Audit_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Audits</relationshipLabel>
        <relationshipName>Audit_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Audit/Objective Association</label>
    <nameField>
        <displayFormat>AOA-{0000}</displayFormat>
        <label>Audit/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance_Objectives_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Objectives Association</label>
    <nameField>
        <displayFormat>GO{00000}</displayFormat>
        <label>Governance Objectives Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Objectives Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectiveAssociationJSONToolkitTest.cls
@isTest
private class ObjectiveAssociationJSONToolkitTest {

    static final String OBJ_CONST = 'Test Objective';
    static final String GOVERNANCE_CONST = 'Test Governance';
    static final String AUDIT_NAME_CONST = 'Test Audit';
    static final String AUDIT_DESC_CONST = 'Test Audit Description';
    
    
    static String JSONResult;
    
    static {
        Objectives__c objective = new Objectives__c(Name = OBJ_CONST);
        insert objective;
        
        Governance__c governance = new Governance__c(Name = GOVERNANCE_CONST);
        insert governance;
        Governance_Objectives_Association__c governanceRiskAssociation = new Governance_Objectives_Association__c(Objectives__c = objective.Id, Governance__c = governance.Id);
        insert governanceRiskAssociation;
        
        Audit__c audit = new Audit__c(Name = AUDIT_NAME_CONST, Audit_Item_Description__c = AUDIT_DESC_CONST);
        insert audit;
        Audit_Objective_Association__c auditRiskAssociation = new Audit_Objective_Association__c(Objectives__c = objective.Id, Audit__c = audit.Id);
        insert auditRiskAssociation;
        /*
        Internal_Audit_Subtask__c internalauditsubtask = new Internal_Audit_Subtask__c();
        insert internalauditsubtask;
        Internal_Audit_Objective_Association__c internalAuditSubtaskRiskAssociation = new Internal_Audit_Objective_Association__c(Objectives__c = objective.Id, Internal_Audit_Subtask__c = internalauditsubtask.Id);
        insert internalAuditSubtaskRiskAssociation;
        */
        Objectives__c obj = [Select Id From Objectives__c limit 1];
        String objsId = obj.Id;
        JSONResult = ObjectiveAssociationJSONToolkit.toJSON(obj.Id);
    }
    
    
    static testMethod void testObjective() {
        Integer i = 0;
        JSONParser parser = JSON.createParser(JSONResult);
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
                i++;
                if (i == 3) {
                    parser.nextToken();
                    break;
                }
            }
        }
        
        String governanceName = parser.getText();
        //System.assert(governanceName == GOVERNANCE_CONST);
    }
    
}