src/objects/Audit__c.object
<CustomObject>
    <label>Audit</label>
    <nameField>
        <label>Audit Element Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Audit_Control_Association__c.object
<CustomObject>
    <fields>
        <fullName>Audit__c</fullName>
        <label>Audit</label>
        <referenceTo>Audit__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Audit_Control_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Audits</relationshipLabel>
        <relationshipName>Audit_Control_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Audit/Control Association</label>
    <nameField>
        <displayFormat>ACA-{0000}</displayFormat>
        <label>Audit/Control Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit/Control Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance__c.object
<CustomObject>
    <fields>
        <fullName>Control_Activity_to_be_Tested__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Control Activity to be Tested</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Compliance</relationshipLabel>
        <relationshipName>Compliance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Control_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Committee Association</label>
    <nameField>
        <displayFormat>CCA{00000}</displayFormat>
        <label>Control Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Compliances</relationshipLabel>
        <relationshipName>Control_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Compliance Association</label>
    <nameField>
        <displayFormat>CC{00000}</displayFormat>
        <label>Control Compliance Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Indicator_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Control_Indicator_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Indicator_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Indicator Association</label>
    <nameField>
        <label>Control Indicator Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control/Indicator Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Vendor_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Control_Vendor_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.  Account Record type must be Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Control_Vendor_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Vendor Association</label>
    <nameField>
        <displayFormat>CVA{00000}</displayFormat>
        <label>Control Vendor Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Vendor Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <recordTypes>
        <fullName>Control</fullName>
        <active>true</active>
        <label>Control</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Controls_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Controls Association</label>
    <nameField>
        <displayFormat>RCA{00000}</displayFormat>
        <label>Risk/Controls Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Controls Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ControlAssociationJSONToolkit.cls
global class ControlAssociationJSONToolkit {
    webservice static String toJSON(String controlID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        categoryNames.add('Compliances');
        categoryNames.add('Vendors');
        categoryNames.add('Indicators');
        categoryNames.add('Committees');
        categoryNames.add('Audits');
        categoryNames.add('Risks');
        
        List<Control_Compliance_Association__c> compliances = [SELECT Controls__r.Id, Controls__r.Name, Compliance__r.Id, Compliance__r.Name from Control_Compliance_Association__c where Controls__r.Id =:controlID];
        List<Control_Vendor_Association__c> vendors = [SELECT Controls__r.Id, Controls__r.Name, Vendor__r.Id, Vendor__r.Name from Control_Vendor_Association__c where Controls__r.Id =:controlID];
        List<Control_Indicator_Association__c> indicators = [SELECT Controls__r.Id, Controls__r.Name, Indicator__r.Id, Indicator__r.Name from Control_Indicator_Association__c where Controls__r.Id =:controlID];
        List<Control_Committee_Association__c> committees = [SELECT Controls__r.Id, Controls__r.Name, Committees__r.Id, Committees__r.Name from Control_Committee_Association__c where Controls__r.Id =:controlID];
        List<Audit_Control_Association__c> audits = [SELECT Controls__r.Id, Controls__r.Name, Audit__r.Id, Audit__r.Name from Audit_Control_Association__c where Controls__r.Id =:controlID];
        List<Risk_Controls_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Controls__r.Id, Controls__r.Name from Risk_Controls_Association__c where Controls__r.Id =:controlID];
        
        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'CONTROL');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                            if (categoryName == 'Risks')
                            {
                                for (Risk_Controls_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Compliances')
                            {
                                for (Control_Compliance_Association__c compliance : compliances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', compliance.Compliance__r.Name);
                                        generator.writeStringField('objectID', compliance.Compliance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                            else if (categoryName == 'Indicators')
                            {
                                for (Control_Indicator_Association__c indicator : indicators)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', indicator.Indicator__r.Name);
                                        generator.writeStringField('objectID', indicator.Indicator__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Committees')
                            {
                                for (Control_Committee_Association__c committee : committees)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', committee.Committees__r.Name);
                                        generator.writeStringField('objectID', committee.Committees__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                            else if (categoryName == 'Vendors')
                            {
                                for (Control_Vendor_Association__c vendor : vendors)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', vendor.Vendor__r.Name);
                                        generator.writeStringField('objectID', vendor.Vendor__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Audits')
                            {
                                for (Audit_Control_Association__c audit : audits)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', audit.Audit__r.Name);
                                        generator.writeStringField('objectID', audit.Audit__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}