src/objects/Audit__c.object
<CustomObject>
    <fields>
        <fullName>Audit_Item_Description__c</fullName>
        <description>Short name describing Audit description</description>
        <inlineHelpText>Enter a brief description of the audit overview</inlineHelpText>
        <label>Audit Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Audit</label>
    <nameField>
        <label>Audit Element Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Audit_Control_Association__c.object
<CustomObject>
    <fields>
        <fullName>Audit__c</fullName>
        <label>Audit</label>
        <referenceTo>Audit__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Audit_Control_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Audits</relationshipLabel>
        <relationshipName>Audit_Control_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Audit/Control Association</label>
    <nameField>
        <displayFormat>ACA-{0000}</displayFormat>
        <label>Audit/Control Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit/Control Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Control_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Committee Association</label>
    <nameField>
        <displayFormat>CCA{00000}</displayFormat>
        <label>Control Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Compliances</relationshipLabel>
        <relationshipName>Control_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Compliance Association</label>
    <nameField>
        <displayFormat>CC{00000}</displayFormat>
        <label>Control Compliance Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Indicator_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Control_Indicator_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Indicator_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Indicator Association</label>
    <nameField>
        <label>Control Indicator Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control/Indicator Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Control_Vendor_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Control_Vendor_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.  Account Record type must be Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Control_Vendor_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Vendor Association</label>
    <nameField>
        <displayFormat>CVA{00000}</displayFormat>
        <label>Control Vendor Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Vendor Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <recordTypes>
        <fullName>Control</fullName>
        <active>true</active>
        <label>Control</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Controls_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Controls Association</label>
    <nameField>
        <displayFormat>RCA{00000}</displayFormat>
        <label>Risk/Controls Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Controls Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor__c.object
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ControlAssociationJSONToolkitTest.cls
@isTest
public class ControlAssociationJSONToolkitTest {
    static final String VENDOR_LOCATION_CONST = 'Test Vendor Location';
    static final String COMPLIANCE_CONST = 'Test Compliance';
    static final String INDICATOR_CONST = 'Test Indicator';
    static final String COMMITTEE_CONST = 'Test Committee';
    static final String AUDIT_CONST = 'Test Audit';
    static final String RISK_CONST = 'Test Risk';
    
    static String JSONResult;
    
    static {
        /*RecordType accountVendorRecordTypeID = [SELECT ID, Name FROM RecordType WHERE Name='rkgrc__Vendor' AND SobjectType='Account' limit 1];*/
        
        Controls__c control = new Controls__c(Name = 'Test');
        insert control;
        
        /*
        Account vendorLocation = new Account(Name = VENDOR_LOCATION_CONST, RecordType=accountVendorRecordTypeID);
        insert vendorLocation;
        Control_Vendor_Association__c controlVendorLocationAssociation = new Control_Vendor_Association__c(Controls__c = control.Id, Vendor__c = vendorLocation.Id);
        insert controlVendorLocationAssociation;
        */
        Compliance__c compliance = new Compliance__c(Name = COMPLIANCE_CONST);
        insert compliance;
        Control_Compliance_Association__c controlComplianceAssociation = new Control_Compliance_Association__c(Controls__c = control.Id, Compliance__c = compliance.Id);
        insert controlComplianceAssociation;
        
        Indicator__c indicator = new Indicator__c(Name = INDICATOR_CONST);
        insert indicator;
        Control_Indicator_Association__c controlIndicatorAssociation = new Control_Indicator_Association__c(Controls__c = control.Id, Indicator__c = indicator.Id);
        insert controlIndicatorAssociation;
        
        Committees__c committee = new Committees__c(Name = COMMITTEE_CONST);
        insert committee;
        Control_Committee_Association__c controlCommitteeAssociation = new Control_Committee_Association__c(Controls__c = control.Id, Committees__c = committee.Id);
        insert controlCommitteeAssociation;
        
        Audit__c audit = new Audit__c(Name = AUDIT_CONST, Audit_Item_Description__c='Test Description');
        insert audit;
        Audit_Control_Association__c controlAuditAssociation = new Audit_Control_Association__c(Controls__c = control.Id, Audit__c = audit.Id);
        insert controlAuditAssociation;
        
        Risk__c risk = new Risk__c(Name = RISK_CONST);
        insert risk;
        Risk_Controls_Association__c controlRiskAssociation = new Risk_Controls_Association__c(Controls__c = control.Id, Risk__c = risk.Id);
        insert controlRiskAssociation;
        
        Controls__c ctrl = [Select Id From Controls__c limit 1];
        String ctrlID = ctrl.Id;
        JSONResult = ControlAssociationJSONToolkit.toJSON(ctrlID);
    }
    
    static testMethod void testVendorLocation() {
        Integer i = 0;
        JSONParser parser = JSON.createParser(JSONResult);
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
                i++;
                if (i == 3) {
                    parser.nextToken();
                    break;
                }
            }
        }
    }
}