src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Committee Association</label>
    <nameField>
        <displayFormat>PCA-{000000}</displayFormat>
        <label>Product/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Governance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Governance Association</label>
    <nameField>
        <displayFormat>PGA-{000000}</displayFormat>
        <label>Product/Governance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Governance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Objective Association</label>
    <nameField>
        <displayFormat>POA-{000000}</displayFormat>
        <label>Product/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRDVLA{000000}</displayFormat>
        <label>Product/Vendor Location Association Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Location__c.object
<CustomObject>
    <label>Vendor Location</label>
    <nameField>
        <label>Vendor Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductAssociationJSONToolkitTest.cls
@isTest
private class ProductAssociationJSONToolkitTest {
	static final String VENDOR_LOCATION_CONST = 'Test Vendor Location';
	static final String GOVERNANCE_CONST = 'Test Governance';
	static final String COMMITTEE_CONST = 'Test Committee';
	static final String OBJECTIVE_CONST = 'Test Objective';
	
	static String JSONResult;
	
	static {
		Product__c product = new Product__c(Name = 'Test');
    	insert product;
    	
    	Vendor_Location__c vendorLocation = new Vendor_Location__c(Name = VENDOR_LOCATION_CONST);
    	insert vendorLocation;
    	Product_Vendor_Location_Association__c productVendorLocationAssociation = new Product_Vendor_Location_Association__c(Product__c = product.Id, Vendor_Location__c = vendorLocation.Id);
    	insert productVendorLocationAssociation;
    	
    	Governance__c governance = new Governance__c(Name = GOVERNANCE_CONST);
    	insert governance;
    	Product_Governance_Association__c productGovernanceAssociation = new Product_Governance_Association__c(Product__c = product.Id, Governance__c = governance.Id);
    	insert productGovernanceAssociation;
    	
    	Committees__c committee = new Committees__c(Name = COMMITTEE_CONST);
    	insert committee;
    	Product_Committee_Association__c productCommitteeAssociation = new Product_Committee_Association__c(Product__c = product.Id, Committees__c = committee.Id);
    	insert productCommitteeAssociation;
    	
    	Objectives__c objective = new Objectives__c(Name = OBJECTIVE_CONST);
    	insert objective;
    	Product_Objective_Association__c productObjectiveAssociation = new Product_Objective_Association__c(Product__c = product.Id, Objectives__c = objective.Id);
    	insert productObjectiveAssociation;
    	
    	Product__c prd = [Select Id From Product__c limit 1];
        String prdId = prd.Id;
        JSONResult = ProductAssociationJSONToolkit.toJSON(prd.Id);
	}
	
    static testMethod void testVendorLocation() {
        Integer i = 0;
        JSONParser parser = JSON.createParser(JSONResult);
        while (parser.nextToken() != null) {
        	if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
				i++;
				if (i == 3) {
					parser.nextToken();
					break;
				}
        	}
        }
        
        String vendorName = parser.getText();
        System.assert(vendorName == VENDOR_LOCATION_CONST);
    }
}