src/objects/Committee_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committee/Contact Associations</relationshipLabel>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Committee/Contact Association</label>
    <nameField>
        <displayFormat>CO{00000}</displayFormat>
        <label>Committee Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Committee/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Contacts</relationshipLabel>
        <relationshipName>Compliance_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Compliance_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance/Contact Association</label>
    <nameField>
        <displayFormat>CCA-{000000}</displayFormat>
        <label>Compliance/Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Location/Contact Associations</relationshipLabel>
        <relationshipName>Location_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RK_Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <referenceTo>rkl__RK_Hierarchy_Node__c</referenceTo>
        <relationshipLabel>Location/Contact Associations</relationshipLabel>
        <relationshipName>Location_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location/Contact Association</label>
    <nameField>
        <displayFormat>LCA{00000}</displayFormat>
        <label>Location/Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Stakeholder_Association__c.object
<CustomObject>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Stakeholders</relationshipLabel>
        <relationshipName>Risk_Stakeholder_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stakeholder__c</fullName>
        <label>Stakeholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Stakeholder</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Stakeholder_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Stakeholder Association</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Risk/Stakeholder Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Stakeholder Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactAssociationJSONToolkit.cls
global class ContactAssociationJSONToolkit {
    webservice static String toJSON(String contactID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        
        categoryNames.add('Committees');
        categoryNames.add('Compliances');
        //categoryNames.add('Governances');
        categoryNames.add('Locations');
        categoryNames.add('Risks');
                
        List<Committee_Contact_Association__c> committees = [SELECT Contact__r.Id, Contact__r.Name, Committees__r.Id, Committees__r.Name from Committee_Contact_Association__c where Contact__r.Id =:contactID];
        List<Compliance_Contact_Association__c> compliances = [SELECT Contact__r.Id, Contact__r.Name, Compliance__r.Id, Compliance__r.Name from Compliance_Contact_Association__c where Contact__r.Id =:contactID];
        //List<Contact_Governance_Association__c> governances = [SELECT Contact__r.Id, Contact__r.Name, Governance__r.Id, Governance__r.Name from Contact_Governance_Association__c where Contact__r.Id =:contactID];
        List<Location_Contact_Association__c> locations = [SELECT Contact__r.Id, Contact__r.Name, RK_Hierarchy__r.Id, RK_Hierarchy__r.Name from Location_Contact_Association__c where Contact__r.Id =:contactID];
        List<Risk_Stakeholder_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Stakeholder__r.Id, Stakeholder__r.Name from Risk_Stakeholder_Association__c where Stakeholder__r.Id =:contactID];
        

        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'CONTROL');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();

                            
                            if (categoryName == 'Committees')
                            {
                                for (Committee_Contact_Association__c committee : committees)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', committee.Committees__r.Name);
                                        generator.writeStringField('objectID', committee.Committees__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                            else if (categoryName == 'Compliances')
                            {
                                for (Compliance_Contact_Association__c compliance : compliances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', compliance.Compliance__r.Name);
                                        generator.writeStringField('objectID', compliance.Compliance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            /*
                            else if (categoryName == 'Governances')
                            {
                                for (Contact_Governance_Association__c governance : governances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', governance.Governance__r.Name);
                                        generator.writeStringField('objectID', governance.Governance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            */
                            
                            else if (categoryName == 'Locations')
                            {
                                for (Location_Contact_Association__c location : locations)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', location.RK_Hierarchy__r.Name);
                                        generator.writeStringField('objectID', location.RK_Hierarchy__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                            else if (categoryName == 'Risks')
                            {
                                for (Risk_Stakeholder_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}