src/objects/Committee_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committee/Contact Associations</relationshipLabel>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Committee/Contact Association</label>
    <nameField>
        <displayFormat>CO{00000}</displayFormat>
        <label>Committee Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Committee/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Control_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Committee Association</label>
    <nameField>
        <displayFormat>CCA{00000}</displayFormat>
        <label>Control Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <recordTypes>
        <fullName>Control</fullName>
        <active>true</active>
        <label>Control</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Indicator_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Indicator_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator/Committee Association</label>
    <nameField>
        <displayFormat>IC{00000}</displayFormat>
        <label>Indicator/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Committee Association</label>
    <nameField>
        <displayFormat>PCA-{000000}</displayFormat>
        <label>Product/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Risk_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Committee Association</label>
    <nameField>
        <displayFormat>RC{00000}</displayFormat>
        <label>Risk/Committee Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommitteeAssociationJSONToolkit.cls
global class CommitteeAssociationJSONToolkit {
    webservice static String toJSON(String committeeID) {

        List<String> categoryNames = new List<String>();
        categoryNames.add('Contacts');
        categoryNames.add('Indicators');
        categoryNames.add('Controls');
        categoryNames.add('Risks');
        categoryNames.add('Products');

        List<Committee_Contact_Association__c> contacts = [SELECT Committees__r.Id, Committees__r.Name, Contact__r.Id, Contact__r.Name FROM Committee_Contact_Association__c WHERE Committees__r.Id =: committeeID];
        List<Indicator_Committee_Association__c> indicators = [SELECT Committees__r.Id, Committees__r.Name, Indicator__r.Id, Indicator__r.Name FROM Indicator_Committee_Association__c WHERE Committees__r.Id =: committeeID];
        List<Control_Committee_Association__c> controls = [SELECT Committees__r.Id, Committees__r.Name, Controls__r.Id, Controls__r.Name FROM Control_Committee_Association__c WHERE Committees__r.Id =: committeeID];
        List<Risk_Committee_Association__c> risks = [SELECT Committees__r.Id, Committees__r.Name, Risk__r.Id, Risk__r.Name FROM Risk_Committee_Association__c WHERE Committees__r.Id =: committeeID];
        List<Product_Committee_Association__c> products = [SELECT Committees__r.Id, Committees__r.Name, Product__r.Id, Product__r.Name FROM Product_Committee_Association__c WHERE Committees__r.Id =: committeeID];

        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'COMMITTEE');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                            if (categoryName == 'Contacts')
                            {
                                for (Committee_Contact_Association__c contact : contacts)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', contact.Contact__r.Name);
                                        generator.writeStringField('objectID', contact.Contact__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Indicators')
                            {
                                for (Indicator_Committee_Association__c indicator : indicators)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', indicator.Indicator__r.Name);
                                        generator.writeStringField('objectID', indicator.Indicator__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Controls')
                            {
                                for (Control_Committee_Association__c control : controls)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', control.Controls__r.Name);
                                        generator.writeStringField('objectID', control.Controls__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Risks')
                            {
                                for (Risk_Committee_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Products')
                            {
                                for (Product_Committee_Association__c product : products)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', product.Product__r.Name);
                                        generator.writeStringField('objectID', product.Product__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();

        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');

        return returnString;
    }
}