src/objects/Committee_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committee/Contact Associations</relationshipLabel>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Committee/Contact Association</label>
    <nameField>
        <displayFormat>CO{00000}</displayFormat>
        <label>Committee Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Committee/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Control_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Control_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Control/Committee Association</label>
    <nameField>
        <displayFormat>CCA{00000}</displayFormat>
        <label>Control Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <recordTypes>
        <fullName>Control</fullName>
        <active>true</active>
        <label>Control</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Indicator_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Indicator_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator/Committee Association</label>
    <nameField>
        <displayFormat>IC{00000}</displayFormat>
        <label>Indicator/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Committee Association</label>
    <nameField>
        <displayFormat>PCA-{000000}</displayFormat>
        <label>Product/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Committees</relationshipLabel>
        <relationshipName>Risk_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Committee Association</label>
    <nameField>
        <displayFormat>RC{00000}</displayFormat>
        <label>Risk/Committee Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommitteeAssociationJSONToolkitTest.cls
@isTest
public class CommitteeAssociationJSONToolkitTest {
  
  static final String CONTACT_CONST = 'Test Contact';
  static final String INDICATOR_CONST = 'Test Indicator';
  static final String CONTROL_CONST = 'Test Control';
  static final String RISK_CONST = 'Test Risk';
  static final String PRODUCT_CONST = 'Test Product';
  
  static String JSONResult;
  
  
  static {
    Committees__c committee = new Committees__c(Name = 'Test');
      insert committee;
     
      Risk__c risk = new Risk__c(Name = RISK_CONST);
      insert risk;
      Risk_Committee_Association__c riskCommitteeAssociation = new Risk_Committee_Association__c(Committees__c = committee.Id, Risk__c = risk.Id);
      insert riskCommitteeAssociation;
      
      Contact contact = new Contact (LastName = CONTACT_CONST);
      insert contact;
      Committee_Contact_Association__c committeeContactAssociation = new Committee_Contact_Association__c(Committees__c = committee.id, Contact__c = contact.id);
      insert committeeContactAssociation;
     
      Controls__c control = new Controls__c(Name = CONTROL_CONST);
      insert control;
      Control_Committee_Association__c controlCommitteeAssociation = new Control_Committee_Association__c(Committees__c = committee.Id, Controls__c = control.Id);
      insert controlCommitteeAssociation;
      
      Indicator__c indicator = new Indicator__c(Name = INDICATOR_CONST);
      insert indicator;
      Indicator_Committee_Association__c indicatorCommitteeAssociation = new Indicator_Committee_Association__c(Committees__c = committee.Id, Indicator__c = indicator.Id);
      insert indicatorCommitteeAssociation;
      
      Product__c product = new Product__c(Name = Product_CONST);
      insert product;
      Product_Committee_Association__c productCommitteeAssociation = new Product_Committee_Association__c(Committees__c = committee.Id, Product__c = product.Id);
      insert productCommitteeAssociation;
      
      JSONResult = CommitteeAssociationJSONToolkit.toJSON(committee.Id);  
      }
      
      
 static testMethod void testCommittee() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String contactName = parser.getText();
    System.assert(contactName == CONTACT_CONST);
  }      
}