src/objects/Committee_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committee/Contact Associations</relationshipLabel>
        <relationshipName>Committee_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Committee/Contact Association</label>
    <nameField>
        <displayFormat>CO{00000}</displayFormat>
        <label>Committee Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Committee/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Contacts</relationshipLabel>
        <relationshipName>Compliance_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Compliance_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance/Contact Association</label>
    <nameField>
        <displayFormat>CCA-{000000}</displayFormat>
        <label>Compliance/Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Location/Contact Associations</relationshipLabel>
        <relationshipName>Location_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RK_Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <referenceTo>rkl__RK_Hierarchy_Node__c</referenceTo>
        <relationshipLabel>Location/Contact Associations</relationshipLabel>
        <relationshipName>Location_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location/Contact Association</label>
    <nameField>
        <displayFormat>LCA{00000}</displayFormat>
        <label>Location/Contact Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location/Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Stakeholder_Association__c.object
<CustomObject>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Stakeholders</relationshipLabel>
        <relationshipName>Risk_Stakeholder_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stakeholder__c</fullName>
        <label>Stakeholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Stakeholder</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Stakeholder_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Stakeholder Association</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Risk/Stakeholder Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Stakeholder Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactAssociationJSONToolkitTest.cls
@isTest
public class ContactAssociationJSONToolkitTest {
  static final String VENDOR_LOCATION_CONST = 'Test Vendor Location';
  static final String COMMITTEE_CONST = 'Test Committee';
  static final String COMPLIANCE_CONST = 'Test Compliance';
  static final String GOVERNANCE_CONST = 'Test Governance';
  static final String Location_CONST = 'Test Location';
  static final String RISK_CONST = 'Test Risk';
  
  static String JSONResult;
  
  static {
    
    Contact contact = new Contact(LastName = 'Test');
      insert contact;
      
      Committees__c committee = new Committees__c(Name = COMMITTEE_CONST);
      insert committee;
      Committee_Contact_Association__c a1 = new Committee_Contact_Association__c(Contact__c = contact.Id, Committees__c = committee.Id);
      insert a1;
            
      Compliance__c compliance = new Compliance__c(Name = COMPLIANCE_CONST);
      insert compliance;
      Compliance_Contact_Association__c a2 = new Compliance_Contact_Association__c(Contact__c = contact.Id, Compliance__c = compliance.Id);
      insert a2;
      /*
      Governance__c governance = new Governance__c(Name = GOVERNANCE_CONST);
      insert governance;
      Contact_Governance_Association__c a3 = new Contact_Governance_Association__c(Contact__c = contact.Id, Governance__c = governance.Id);
      insert a3;
      */
      rkl__RK_Hierarchy_Node__c location = new rkl__RK_Hierarchy_Node__c(Name = LOCATION_CONST, rkl__Node_Key__c = '0');
      insert location;
      Location_Contact_Association__c a4 = new Location_Contact_Association__c(Contact__c = contact.Id, RK_Hierarchy__c = location.Id);
      insert a4;
      
      Risk__c risk = new Risk__c(Name = RISK_CONST);
      insert risk;
      Risk_Stakeholder_Association__c a5 = new Risk_Stakeholder_Association__c(Stakeholder__c = contact.Id, Risk__c = risk.Id);
      insert a5;
      
      Contact cntct = [Select Id From Contact limit 1];
        String cntctId = cntct.Id;
        JSONResult = ContactAssociationJSONToolkit.toJSON(cntctId);
  }

  static testMethod void testContact() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String complianceName = parser.getText();
    //System.assert(complianceName == COMPLIANCE_CONST);
  }

}