src/objects/Committees__c.object
<CustomObject>
    <label>Committees old</label>
    <nameField>
        <label>Committee&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Governance</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Governance__c.Parent_or_Subsidiary_Governance__c</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Subsidiary Governance</relationshipLabel>
        <relationshipName>Governance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Committee_Association__c.object
<CustomObject>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Committees__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Committee Associations</relationshipLabel>
        <relationshipName>Product_Committee_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Committee Association</label>
    <nameField>
        <displayFormat>PCA-{000000}</displayFormat>
        <label>Product/Committee Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Committee Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Governance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Governance Association</label>
    <nameField>
        <displayFormat>PGA-{000000}</displayFormat>
        <label>Product/Governance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Governance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Objective Associations</relationshipLabel>
        <relationshipName>Product_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Objective Association</label>
    <nameField>
        <displayFormat>POA-{000000}</displayFormat>
        <label>Product/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRDVLA{000000}</displayFormat>
        <label>Product/Vendor Location Association Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Location__c.object
<CustomObject>
    <label>Vendor Location</label>
    <nameField>
        <label>Vendor Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductAssociationJSONToolkit.cls
global class ProductAssociationJSONToolkit {
    webservice static String toJSON(String productId)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        categoryNames.add('Vendor Locations');
        categoryNames.add('Governances');
        categoryNames.add('Committees');
        categoryNames.add('Objectives');

        
        List<Product_Vendor_Location_Association__c> vendorLocations = [SELECT Product__r.Id, Product__r.Name, Vendor_Location__r.Id, Vendor_Location__r.Name from Product_Vendor_Location_Association__c where Product__r.Id =:productId];
        List<Product_Governance_Association__c> governances = [SELECT Product__r.Id, Product__r.Name, Governance__r.Id, Governance__r.Name from Product_Governance_Association__c where Product__r.Id =:productId];
        List<Product_Committee_Association__c> committees = [SELECT Product__r.Id, Product__r.Name, Committees__r.Id, Committees__r.Name from Product_Committee_Association__c where Product__r.Id =:productId];
        List<Product_Objective_Association__c> objectives = [SELECT Product__r.Id, Product__r.Name, Objectives__r.Id, Objectives__r.Name from Product_Objective_Association__c where Product__r.Id =:productId];

        
        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'PRODUCT');
			generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
						generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                            if (categoryName == 'Vendor Locations')
                            {
                                for (Product_Vendor_Location_Association__c vendorLocation : vendorLocations)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', vendorLocation.Vendor_Location__r.Name);
                                        generator.writeStringField('objectID', vendorLocation.Vendor_Location__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Governances')
                            {
                                for (Product_Governance_Association__c governance : governances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', governance.Governance__r.Name);
                                        generator.writeStringField('objectID', governance.Governance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Committees')
                            {
                                for (Product_Committee_Association__c committee : committees)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', committee.Committees__r.Name);
                                        generator.writeStringField('objectID', committee.Committees__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Objectives')
                            {
                                for (Product_Objective_Association__c objective : objectives)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', objective.Objectives__r.Name);
                                        generator.writeStringField('objectID', objective.Objectives__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
		
        return returnString;
    }
}