src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Governance</relationshipLabel>
        <relationshipName>Governance_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Governance_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Compliance Association</label>
    <nameField>
        <displayFormat>GCA{000000}</displayFormat>
        <label>Governance/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Indicators_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Governance_Indicators_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Indicators_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Indicators Association</label>
    <nameField>
        <displayFormat>GI{00000}</displayFormat>
        <label>Governance Indicators Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Indicators Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Objectives_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Objectives Association</label>
    <nameField>
        <displayFormat>GO{00000}</displayFormat>
        <label>Governance Objectives Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Objectives Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Risk_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Governance_Risks_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risks__c</fullName>
        <label>Risks</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Risks_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Risk Association</label>
    <nameField>
        <displayFormat>GA{00000}</displayFormat>
        <label>Governance/Risk Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Risk Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Governance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Governance Association</label>
    <nameField>
        <displayFormat>PGA-{000000}</displayFormat>
        <label>Product/Governance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Governance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GovernanceAssociationJSONToolkitTest.cls
@isTest
public class GovernanceAssociationJSONToolkitTest {
  static final String COMPLIANCE_CONST = 'Test Compliance';
  static final String INDICATOR_CONST = 'Test Indicator';
  static final String OBJECTIVE_CONST = 'Test Objective';
  static final String RISK_CONST = 'Test Risk';
  static final String PRODUCT_CONST = 'Test Product';

  static String JSONResult;

  static {
    Governance__c governance = new Governance__c(Name = 'Test Governance');
    insert governance;

    Compliance__c compliance = new Compliance__c(Name = COMPLIANCE_CONST);
    insert compliance;
    Governance_Compliance_Association__c governanceComplianceAssoc = new Governance_Compliance_Association__c(Governance__c = governance.Id, Compliance__c = compliance.Id);
    insert governanceComplianceAssoc;

    Indicator__c indicator = new Indicator__c(Name = INDICATOR_CONST);
    insert indicator;
    Governance_Indicators_Association__c governanceIndicatorsAssoc = new Governance_Indicators_Association__c(Governance__c = governance.Id, Indicator__c = indicator.Id);
    insert governanceIndicatorsAssoc;

    Objectives__c objective = new Objectives__c(Name = OBJECTIVE_CONST);
    insert objective;
    Governance_Objectives_Association__c governanceObjectivesAssoc = new Governance_Objectives_Association__c(Governance__c = governance.Id, Objectives__c = objective.Id);
    insert governanceObjectivesAssoc;

    Risk__c risk = new Risk__c(Name = RISK_CONST);
    insert risk;
    Governance_Risk_Association__c governanceRiskAssoc = new Governance_Risk_Association__c(Governance__c = governance.Id, Risks__c = risk.Id);
    insert governanceRiskAssoc;

    Product__c product = new Product__c(Name = PRODUCT_CONST);
    insert product;
    Product_Governance_Association__c productGovernanceAssoc = new Product_Governance_Association__c(Governance__c = governance.Id, Product__c = product.Id);
    insert productGovernanceAssoc;

    JSONResult = GovernanceAssociationJSONToolkit.toJSON(governance.Id);
  }

  static testMethod void testGovernance() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String complianceName = parser.getText();
    System.assert(complianceName == COMPLIANCE_CONST);
  }
}