src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Governance</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Governance__c.Parent_or_Subsidiary_Governance__c</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Subsidiary Governance</relationshipLabel>
        <relationshipName>Governance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Governance</label>
    <nameField>
        <label>Governance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Governance_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Governance</relationshipLabel>
        <relationshipName>Governance_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Governance_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Compliance Association</label>
    <nameField>
        <displayFormat>GCA{000000}</displayFormat>
        <label>Governance/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Indicators_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Governance_Indicators_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Indicators_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Indicators Association</label>
    <nameField>
        <displayFormat>GI{00000}</displayFormat>
        <label>Governance Indicators Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Indicators Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Objectives_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Objectives_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Objectives Association</label>
    <nameField>
        <displayFormat>GO{00000}</displayFormat>
        <label>Governance Objectives Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Objectives Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Governance_Risk_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Governance_Risks_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risks__c</fullName>
        <label>Risks</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Governances</relationshipLabel>
        <relationshipName>Governance_Risks_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Governance/Risk Association</label>
    <nameField>
        <displayFormat>GA{00000}</displayFormat>
        <label>Governance/Risk Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Governance/Risk Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Governance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Governance__c</fullName>
        <label>Governance</label>
        <referenceTo>Governance__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Governance Associations</relationshipLabel>
        <relationshipName>Product_Governance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Governance Association</label>
    <nameField>
        <displayFormat>PGA-{000000}</displayFormat>
        <label>Product/Governance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Governance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GovernanceAssociationJSONToolkit.cls
global class GovernanceAssociationJSONToolkit {
  webservice static String toJSON(String governanceID) {

    List<String> categoryNames = new List<String>();
    categoryNames.add('Compliances');
    categoryNames.add('Indicators');
    categoryNames.add('Objectives');
    categoryNames.add('Risks');
    categoryNames.add('Products');

    List<Governance_Compliance_Association__c> compliances = [SELECT Governance__r.Id, Governance__r.Name, Compliance__r.Id, Compliance__r.Name FROM Governance_Compliance_Association__c WHERE Governance__r.Id =: governanceID];
    List<Governance_Indicators_Association__c> indicators = [SELECT Governance__r.Id, Governance__r.Name, Indicator__r.Id, Indicator__r.Name FROM Governance_Indicators_Association__c WHERE Governance__r.Id =: governanceID];
    List<Governance_Objectives_Association__c> objectives = [SELECT Governance__r.Id, Governance__r.Name, Objectives__r.Id, Objectives__r.Name FROM Governance_Objectives_Association__c WHERE Governance__r.Id =: governanceID];
    List<Governance_Risk_Association__c> risks = [SELECT Governance__r.Id, Governance__r.Name, Risks__r.Id, Risks__r.Name FROM Governance_Risk_Association__c WHERE Governance__r.Id =: governanceID];
    List<Product_Governance_Association__c> products = [SELECT Governance__r.Id, Governance__r.Name, Product__r.Id, Product__r.Name FROM Product_Governance_Association__c WHERE Governance__r.Id =: governanceID];

    JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'GOVERNANCE');
      generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
            generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                            if (categoryName == 'Compliances')
                            {
                                for (Governance_Compliance_Association__c compliance : compliances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', compliance.Compliance__r.Name);
                                        generator.writeStringField('objectID', compliance.Compliance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Indicators')
                            {
                                for (Governance_Indicators_Association__c indicator : indicators)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', indicator.Indicator__r.Name);
                                        generator.writeStringField('objectID', indicator.Indicator__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Objectives')
                            {
                                for (Governance_Objectives_Association__c objective : objectives)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', objective.Objectives__r.Name);
                                        generator.writeStringField('objectID', objective.Objectives__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Risks')
                            {
                                for (Governance_Risk_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risks__r.Name);
                                        generator.writeStringField('objectID', risk.Risks__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Products')
                            {
                                for (Product_Governance_Association__c product : products)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', product.Product__r.Name);
                                        generator.writeStringField('objectID', product.Product__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();

        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');

        return returnString;
  }
}