src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation__c.object
<CustomObject>
    <description>Legal Management</description>
    <label>Litigation</label>
    <nameField>
        <label>Litigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Litigation_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Compliance Association</label>
    <nameField>
        <displayFormat>LCA-{000000}</displayFormat>
        <label>Litigation/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Litigation_Risk_Association__c.object
<CustomObject>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Litigation_Risk_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Risk_Association</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Risk Association</label>
    <nameField>
        <displayFormat>LRA-{000000}</displayFormat>
        <label>Litigation/Risk Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Risk Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Litigation_Violation_Association__c.object
<CustomObject>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Violations</relationshipLabel>
        <relationshipName>Litigation_Violation_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Violation__c</fullName>
        <label>Violation</label>
        <referenceTo>Violation__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Violation_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Violation Association</label>
    <nameField>
        <displayFormat>LVA-{000000}</displayFormat>
        <label>Litigation/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Violation Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Violation__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Violation</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Violation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LitigationAssociationJSONToolkit.cls
global class LitigationAssociationJSONToolkit {
    webservice static String toJSON(String litigationID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        
        categoryNames.add('Compliances');
        categoryNames.add('Risks');
        categoryNames.add('Violations');
        
        List<Litigation_Compliance_Association__c> compliances = [SELECT Litigation__r.Id, Litigation__r.Name, Compliance__r.Id, Compliance__r.Name from Litigation_Compliance_Association__c where Litigation__r.Id =:litigationID];
        List<Litigation_Risk_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Litigation__r.Id, Litigation__r.Name from Litigation_Risk_Association__c where Litigation__r.Id =:litigationID];
        List<Litigation_Violation_Association__c> violations = [SELECT Litigation__r.Id, Litigation__r.Name, Violation__r.Id, Violation__r.Name from Litigation_Violation_Association__c where Litigation__r.Id =:litigationID];
  


        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'LITIGATION');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                           
                           
                            if (categoryName == 'Compliances')
                            {
                                for (Litigation_Compliance_Association__c compliance: compliances)
                                {
                                    generator.writeStartObject();
                                       generator.writeStringField('name', compliance.Compliance__r.Name);
                                       generator.writeStringField('objectID', compliance.Compliance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Violation')
                            {
                                for (Litigation_Violation_Association__c violation : violations)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', violation.Violation__r.Name);
                                        generator.writeStringField('objectID', violation.Violation__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Risks')
                            {
                                for (Litigation_Risk_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                         generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}