src/objects/Compliance__c.object
<CustomObject>
    <fields>
        <fullName>Control_Activity_to_be_Tested__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Control Activity to be Tested</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Compliance</relationshipLabel>
        <relationshipName>Compliance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>GL_Short_Description__c</fullName>
        <label>GL Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>General Ledger</label>
    <nameField>
        <label>General Ledger Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location_Project_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Locations</relationshipLabel>
        <relationshipName>Location_Project_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RK_Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <referenceTo>rkl__RK_Hierarchy_Node__c</referenceTo>
        <relationshipLabel>Location/Project Associations</relationshipLabel>
        <relationshipName>Location_Project_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location/Project Association</label>
    <nameField>
        <displayFormat>LP{00000}</displayFormat>
        <label>Location/Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location/Project Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Compliance_Association</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Compliances</relationshipLabel>
        <relationshipName>Project_Compliance_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Compliance Association</label>
    <nameField>
        <displayFormat>CA{00000}</displayFormat>
        <label>Project/Compliance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Compliance Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_GL_Association__c.object
<CustomObject>
    <fields>
        <fullName>General_Ledger__c</fullName>
        <label>General Ledger</label>
        <referenceTo>General_Ledger__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_GL_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated General Ledgers</relationshipLabel>
        <relationshipName>Project_GL_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/GL Association</label>
    <nameField>
        <displayFormat>PGL{00000}</displayFormat>
        <label>Project/GL Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/GL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Indicators_Association__c.object
<CustomObject>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Indicators_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Project_Indicators_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Indicators Association</label>
    <nameField>
        <displayFormat>PI{00000}</displayFormat>
        <label>Project/Indicator Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Indicators Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Objective Association</label>
    <nameField>
        <displayFormat>PO{00000}</displayFormat>
        <label>Project/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Vendor_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Vendor_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. Account Record type must be Vendor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Vendor_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Vendor Association</label>
    <nameField>
        <displayFormat>PVA{00000}</displayFormat>
        <label>Project/Vendor Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Vendor Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Controls_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Controls Association</label>
    <nameField>
        <displayFormat>RCA{00000}</displayFormat>
        <label>Risk/Controls Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Controls Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk_Project_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Project_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Risk_Project_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Project Association</label>
    <nameField>
        <displayFormat>RP{00000}</displayFormat>
        <label>Risk/Project Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Project Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectAssociationJSONToolkit.cls
global class ProjectAssociationJSONToolkit{
     webservice static String toJSON(String projectID)
    {
        //Project/Compliance Association
        //Project/GL Association
        //Project/Indicators Association
        //Project/Objective Association
        //Project/Vendor Association
        //Risk/Project Association
        //Location/Project Association
        
        
        List<String> categoryNames = new List<String>();
        categoryNames.add('Risks');
        categoryNames.add('Vendors');
        categoryNames.add('Objectives');
        categoryNames.add('Indicators');
        categoryNames.add('GLs');
        categoryNames.add('Compliance');
        categoryNames.add('Locations');
        
        List<Risk_Project_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Project__r.Id, Project__r.Name from Risk_Project_Association__c where Project__r.Id =:projectID];
        List<Project_Vendor_Association__c> vendors = [SELECT Project__r.Id, Project__r.Name, Vendor__r.Id, Vendor__r.Name from Project_Vendor_Association__c where Project__r.Id =:projectID];
        List<Project_Objective_Association__c> objectives = [SELECT Project__r.Id, Project__r.Name, Objectives__r.Id, Objectives__r.Name from Project_Objective_Association__c where Project__r.Id =:projectID];
        List<Project_Indicators_Association__c> indicators = [SELECT Project__r.Id, Project__r.Name, Indicator__r.Id, Indicator__r.Name from Project_Indicators_Association__c where Project__r.Id =:projectID];
        List<Project_GL_Association__c> gls = [SELECT Project__r.Id, Project__r.Name, General_Ledger__r.Id, General_Ledger__r.Name, General_Ledger__r.GL_Short_Description__c from Project_GL_Association__c where Project__r.Id =:projectID];
        List<Project_Compliance_Association__c> compliances = [SELECT Project__r.Id, Project__r.Name, Compliance__r.Id, Compliance__r.Name from Project_Compliance_Association__c where Project__r.Id =:projectID];
        List<Location_Project_Association__c> locations = [SELECT Project__r.Id, Project__r.Name, RK_Hierarchy__r.Id, RK_Hierarchy__r.Name from Location_Project_Association__c where Project__r.Id =:projectID];
        
        List<ID> matchingRiskIDs = new List<ID>();
        for (Risk_Project_Association__c riskProjRelationship : risks)
        {
            matchingRiskIDs.add(riskProjRelationship.Risk__r.Id);
        }
        
        List<Risk_Controls_Association__c> riskControls = [SELECT Risk__r.id, Risk__r.Name, Controls__r.Name, Controls__r.Id from Risk_Controls_Association__c where Risk__r.ID IN :matchingRiskIDs];
        
        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'Project');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                            if (categoryName == 'Risks')
                            {
                                for (Risk_Project_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeFieldname('children');
                                        String objectName = risk.Risk__r.Name;
                                        generator.writeStartArray();
                                            for (Risk_Controls_Association__c riskControlAssoc : riskControls)
                                            {
                                                if (riskControlAssoc.Risk__r.ID == risk.Risk__r.ID)
                                                {
                                                    generator.writeStartObject();
                                                        generator.writeStringField('name', riskControlAssoc.Controls__r.Name);
                                                        generator.writeStringField('objectID', riskControlAssoc.Controls__r.ID);
                                                    generator.writeEndObject();
                                                    objectName = risk.Risk__r.Name + ' - Controls';
                                                }
                                            }
                                        generator.writeEndArray();
                                        generator.writeStringField('name', objectName);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Vendors')
                            {
                                for (Project_Vendor_Association__c vendor : vendors)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', vendor.Vendor__r.Name);
                                        generator.writeStringField('objectID', vendor.Vendor__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Objectives')
                            {
                                for (Project_Objective_Association__c objective : objectives)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', objective.Objectives__r.Name);
                                        generator.writeStringField('objectID', objective.Objectives__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Indicators')
                            {
                                for (Project_Indicators_Association__c indicator : indicators)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', indicator.Indicator__r.Name);
                                        generator.writeStringField('objectID', indicator.Indicator__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'GLs')
                            {
                                for (Project_GL_Association__c gl : gls)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', gl.General_Ledger__r.Name);
                                        generator.writeStringField('objectID', gl.General_Ledger__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Compliance')
                            {
                                for (Project_Compliance_Association__c compliance : compliances)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', compliance.Compliance__r.Name);
                                        generator.writeStringField('objectID', compliance.Compliance__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Locations')
                            {
                                for (Location_Project_Association__c location : locations)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', location.RK_Hierarchy__r.Name);
                                        generator.writeStringField('objectID', location.RK_Hierarchy__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                        generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        System.debug(returnString);
        return returnString;
    }
}