src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Controls__c.object
<CustomObject>
    <label>Control</label>
    <nameField>
        <label>Controls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <recordTypes>
        <fullName>Control</fullName>
        <active>true</active>
        <label>Control</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>GL_Short_Description__c</fullName>
        <label>GL Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>General Ledger</label>
    <nameField>
        <label>General Ledger Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicator__c.object
<CustomObject>
    <label>Indicator</label>
    <nameField>
        <label>Indicators Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location_Project_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Locations</relationshipLabel>
        <relationshipName>Location_Project_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RK_Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <referenceTo>rkl__RK_Hierarchy_Node__c</referenceTo>
        <relationshipLabel>Location/Project Associations</relationshipLabel>
        <relationshipName>Location_Project_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location/Project Association</label>
    <nameField>
        <displayFormat>LP{00000}</displayFormat>
        <label>Location/Project Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location/Project Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objectives__c.object
<CustomObject>
    <description>The Objectives of the entity. This should contain all the significant objectives the organization wants to achieve. The Risks to these objectives will be linked so that the Objective Owner is aware of the potential to not achieve the objectives and to be able to take action.</description>
    <label>Objectives</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Compliance_Association</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Compliances</relationshipLabel>
        <relationshipName>Project_Compliance_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Compliance Association</label>
    <nameField>
        <displayFormat>CA{00000}</displayFormat>
        <label>Project/Compliance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Compliance Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_GL_Association__c.object
<CustomObject>
    <fields>
        <fullName>General_Ledger__c</fullName>
        <label>General Ledger</label>
        <referenceTo>General_Ledger__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_GL_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated General Ledgers</relationshipLabel>
        <relationshipName>Project_GL_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/GL Association</label>
    <nameField>
        <displayFormat>PGL{00000}</displayFormat>
        <label>Project/GL Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/GL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Indicators_Association__c.object
<CustomObject>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <referenceTo>Indicator__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Indicators_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Indicators</relationshipLabel>
        <relationshipName>Project_Indicators_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Indicators Association</label>
    <nameField>
        <displayFormat>PI{00000}</displayFormat>
        <label>Project/Indicator Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Indicators Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Objective_Association__c.object
<CustomObject>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <referenceTo>Objectives__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Objectives</relationshipLabel>
        <relationshipName>Project_Objective_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Objective Association</label>
    <nameField>
        <displayFormat>PO{00000}</displayFormat>
        <label>Project/Objective Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Objective Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Vendor_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Vendor_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project/Vendor Association</label>
    <nameField>
        <displayFormat>PVA{00000}</displayFormat>
        <label>Project/Vendor Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project/Vendor Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Controls_Association__c.object
<CustomObject>
    <fields>
        <fullName>Controls__c</fullName>
        <label>Controls</label>
        <referenceTo>Controls__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Controls</relationshipLabel>
        <relationshipName>Risk_Controls_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Controls Association</label>
    <nameField>
        <displayFormat>RCA{00000}</displayFormat>
        <label>Risk/Controls Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Controls Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk_Project_Association__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Project_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Projects</relationshipLabel>
        <relationshipName>Risk_Project_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Project Association</label>
    <nameField>
        <displayFormat>RP{00000}</displayFormat>
        <label>Risk/Project Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Project Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Location__c.object
<CustomObject>
    <label>Vendor Location</label>
    <nameField>
        <label>Vendor Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectAssociationJSONToolkitTest.cls
@isTest
public class ProjectAssociationJSONToolkitTest {
    static final String RISK_CONST = 'Test Risk';
    static final String VENDOR_LOCATION_CONST = 'Test Vendor Location';
    static final String OBJECTIVE_CONST = 'Test Objective';
    static final String INDICATOR_CONST = 'Test Indicator';
    static final String GL_CONST = 'Test GL';
    static final String COMPLIANCE_CONST = 'Test Compliance';
    static final String LOCATION_CONST = 'Test Location';
    
    static String JSONResult;
    
    static {
        Project__c project = new Project__c(Name = 'Test');
        insert project;
        
        /*
        Vendor_Location__c vendorLocation = new Vendor_Location__c(Name = VENDOR_LOCATION_CONST);
        insert vendorLocation;
        Project_Vendor_Association__c productVendorLocationAssociation = new Project_Vendor_Association__c(Product__c = product.Id, Vendor_Location__c = vendorLocation.Id);
        insert productVendorLocationAssociation;
        */
        
        Risk__c risk = new Risk__c(Name = RISK_CONST);
        insert risk;
        Risk_Project_Association__c projectRiskAssociation = new Risk_Project_Association__c(Project__c = project.Id, Risk__c = risk.Id);
        insert projectRiskAssociation;
        
        Controls__c control = new Controls__c(Name = 'Test Control');
        insert control;
        Risk_Controls_Association__c riskControlAssociation = new Risk_Controls_Association__c(Risk__c = risk.id, Controls__c = control.id);
        insert riskControlAssociation;
        
        Objectives__c objective = new Objectives__c(Name = OBJECTIVE_CONST);
        insert objective;
        Project_Objective_Association__c projectObjectiveAssociation = new Project_Objective_Association__c(Project__c = project.Id, Objectives__c = objective.Id);
        insert projectObjectiveAssociation;
        
        Indicator__c indicator = new Indicator__c(Name = INDICATOR_CONST);
        insert indicator;
        Project_Indicators_Association__c projectIndicatorAssociation = new Project_Indicators_Association__c(Project__c = project.Id, Indicator__c = indicator.Id);
        insert projectIndicatorAssociation;
        
        General_Ledger__c gl = new General_Ledger__c(Name = GL_CONST, GL_Short_Description__c='Test Description');
        insert gl;
        Project_GL_Association__c projectGLAssociation = new Project_GL_Association__c(Project__c = project.Id, General_Ledger__c = gl.Id);
        insert projectGLAssociation;
        
        Compliance__c compliance = new Compliance__c(Name = COMPLIANCE_CONST);
        insert compliance;
        Project_Compliance_Association__c projectComplianceAssociation = new Project_Compliance_Association__c(Project__c = project.Id, Compliance__c = compliance.Id);
        insert projectComplianceAssociation;
        
        rkl__RK_Hierarchy_Node__c location = new rkl__RK_Hierarchy_Node__c(Name = LOCATION_CONST, rkl__Node_Key__c='23asd', rkl__Node_Level__c=1);
        insert location;
        Location_Project_Association__c projectLocationAssociation = new Location_Project_Association__c(Project__c = project.Id, RK_Hierarchy__c = location.id);
        insert projectLocationAssociation;
        
        Project__c prjt = [Select Id From Project__c limit 1];
        String prjtId = prjt.Id;
        JSONResult = ProjectAssociationJSONToolkit.toJSON(prjtId);
    }
    
    static testMethod void testVendorLocation() {
        Integer i = 0;
        JSONParser parser = JSON.createParser(JSONResult);
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
                i++;
                if (i == 3) {
                    parser.nextToken();
                    break;
                }
            }
        }
        
        String vendorName = parser.getText();
    }
}