src/objects/Compliance__c.object
<CustomObject>
    <label>Compliance</label>
    <nameField>
        <label>Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation__c.object
<CustomObject>
    <description>Legal Management</description>
    <label>Litigation</label>
    <nameField>
        <label>Litigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Litigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation_Compliance_Association__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Compliance_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Compliance</relationshipLabel>
        <relationshipName>Litigation_Compliance_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Compliance Association</label>
    <nameField>
        <displayFormat>LCA-{000000}</displayFormat>
        <label>Litigation/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Compliance Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Litigation_Risk_Association__c.object
<CustomObject>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Litigation_Risk_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Risk_Association</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Risk Association</label>
    <nameField>
        <displayFormat>LRA-{000000}</displayFormat>
        <label>Litigation/Risk Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Risk Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Litigation_Violation_Association__c.object
<CustomObject>
    <fields>
        <fullName>Litigation__c</fullName>
        <label>Litigation</label>
        <referenceTo>Litigation__c</referenceTo>
        <relationshipLabel>Associated Violations</relationshipLabel>
        <relationshipName>Litigation_Violation_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Violation__c</fullName>
        <label>Violation</label>
        <referenceTo>Violation__c</referenceTo>
        <relationshipLabel>Associated Litigation</relationshipLabel>
        <relationshipName>Litigation_Violation_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Litigation/Violation Association</label>
    <nameField>
        <displayFormat>LVA-{000000}</displayFormat>
        <label>Litigation/Compliance Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation/Violation Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Violation__c.object
<CustomObject>
    <fields>
        <fullName>Compliance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance</label>
        <referenceTo>Compliance__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Violation</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Violation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LitigationAssociationJSONToolkitTest.cls
@isTest
public class LitigationAssociationJSONToolkitTest {
  
  static final String COMPLIANCE_CONST = 'Test Compliance';
  static final String RISK_CONST = 'Test Risk';
  static final String VIOLATION_CONST = 'Test Violation';
  
  static String JSONResult;
  
  
  static {
    Litigation__c litigation = new Litigation__c(Name = 'Test');
      insert litigation;
     
      Risk__c risk = new Risk__c(Name = RISK_CONST);
      insert risk;
      Litigation_Risk_Association__c litigationRiskAssociation = new Litigation_Risk_Association__c(Litigation__c = litigation.Id, Risk__c = risk.Id);
      insert litigationRiskAssociation;
      
      Compliance__c compliance = new Compliance__c(Name = Compliance_CONST);
      insert compliance;
      Litigation_Compliance_Association__c litigationComplianceAssociation = new Litigation_Compliance_Association__c(Litigation__c = litigation.id, Compliance__c = compliance.id);
      insert litigationComplianceAssociation;
     
      Violation__c violation = new Violation__c();
      insert violation;
      Litigation_Violation_Association__c litigationViolationAssociation = new Litigation_Violation_Association__c(Litigation__c = litigation.Id, Violation__c = violation.Id);
      insert litigationViolationAssociation;
      
      JSONResult = LitigationAssociationJSONToolkit.toJSON(litigation.Id);  
      }
      
      
 static testMethod void testLitigation() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String riskName = parser.getText();
    //System.assert(riskName == RISK_CONST);
  } 

}