src/objects/Correlation__c.object
<CustomObject>
    <description>Milliman Correlation object for Correlaton Matrix</description>
    <fields>
        <fullName>Correlation__c</fullName>
        <label>Correlation</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Matrix__c</fullName>
        <label>Matrix</label>
        <referenceTo>Matrix__c</referenceTo>
        <relationshipLabel>Correlations</relationshipLabel>
        <relationshipName>Correlations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk1__c</fullName>
        <label>Risk</label>
        <referenceTo>MLN_Risk__c</referenceTo>
        <relationshipLabel>Correlations</relationshipLabel>
        <relationshipName>Correlations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risked</label>
        <referenceTo>MLN_Risk__c</referenceTo>
        <relationshipLabel>Correlations (Risk)</relationshipLabel>
        <relationshipName>Correlations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Correlation</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correlations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Matrix__c.object
<CustomObject>
    <description>MLN Matrix custom object</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Matrix__c</fullName>
        <label>Type of Matrix</label>
        <picklist>
            <picklistValues>
                <fullName>Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Likelihood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Matrix</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MLN_Risk__c.object
<CustomObject>
    <description>MillimanGRC Risk Custom Object</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Brief description of this risk</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CorrelationMatrixControllerTest.cls
@isTest
public class CorrelationMatrixControllerTest{
    private static testmethod void runTest(){
        List<MLN_Risk__c> riskList = new List<MLN_Risk__c>();
        MLN_Risk__c risk;
        risk = new MLN_Risk__c(Name='Test Risk');
        insert risk;
        
        MLN_Risk__c risk1;
        risk1 = new MLN_Risk__c(Name='Test Risk1');
        insert risk1;
        
        Matrix__c mat = new Matrix__c(Description__c = 'Test',Type_of_Matrix__c='Likelihood');
        insert mat;
        
        Correlation__c cor = new Correlation__c(Correlation__c = 1,Matrix__c=mat.Id,Risk1__c = risk.Id,Risk2__c = risk1.Id);   
        insert cor;
        
        Correlation__c cor1 = new Correlation__c(Correlation__c = 1,Matrix__c=mat.Id,Risk1__c = risk1.Id,Risk2__c = risk.Id);   
        insert cor1;
        
        
        ApexPages.currentPage().getParameters().put('matrixID',mat.id);
        CorrelationMatrixController CMC = new CorrelationMatrixController();
        CMC.getRFoptions();
        CMC.getMXoptions() ;
        CMC.getCorrelationMap();
        CMC.filterRiskList();
        CMC.selCurMat = mat.Id;
        CMC.filterEXTMX();
        //CMC.saveMatrix();
        CMC.resetMatrix();
        CMC.RisksWithFilter();
        CMC.deleteMatrix();
        
        
        
    }
}