src/objects/ERM_to_FM__c.object
<CustomObject>
    <fields>
        <fullName>Memo_Created_By__c</fullName>
        <label>Memo Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memo_Date__c</fullName>
        <label>Memo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Memo_Description__c</fullName>
        <label>Memo Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ERM to FM</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERM to FM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERM_to_FM_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Detailed_Structural_Stochastic_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Detailed Structural Stochastic Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERM_Program_Identified_Risks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERM Program Identified Risks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERM_Risks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERM Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERM_to_FM__c</fullName>
        <label>ERM to FM</label>
        <referenceTo>ERM_to_FM__c</referenceTo>
        <relationshipLabel>ERM to FM Risks</relationshipLabel>
        <relationshipName>ERM_to_FM_Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Explanation__c</fullName>
        <label>Explanation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FM_Specific_Risks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FM Specific Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Model_Approach__c</fullName>
        <label>Model Approach</label>
        <picklist>
            <picklistValues>
                <fullName>Detailed Structural Stochastic Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residual Standard Deviation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simple Stochastic Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERM Program Identified Risks</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residual_Standard_Deviation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residual Standard Deviation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>MLN_Risk__c</referenceTo>
        <relationshipLabel>ERM to FM Risks</relationshipLabel>
        <relationshipName>ERM_to_FM_Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Simple_Stochastic_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Simple Stochastic Model</label>
        <type>Checkbox</type>
    </fields>
    <label>ERM to FM Risk</label>
    <nameField>
        <displayFormat>EDR-{00000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERM to FM Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MLN_Risk__c.object
<CustomObject>
    <description>MillimanGRC Risk Custom Object</description>
    <label>Risk</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReconciliationMemoController.cls
public class ReconciliationMemoController{
    
    public ERM_to_FM__c erm {get; set;}
    public MLN_Risk__c newRiskFactor {get; set;}
    public ERM_to_FM_Risk__c addRiskFactor {get; set;}
    
    ID ermID = ApexPages.currentPage().getParameters().get('Id');
    
    public ReconciliationMemoController(ApexPages.StandardController con){
        ERM_to_FM__c erm = [Select e.Name, e.Memo_Description__c, e.Memo_Date__c, e.Memo_Created_By__c, e.Id From ERM_to_FM__c e where ID =:ermID];
        newRiskFactor = new MLN_Risk__c();
        addRiskFactor = new ERM_to_FM_Risk__c();
    }
    
    public List<ERM_to_FM_Risk__c> ermList{get; set;}
    
    public List<ERM_to_FM_Risk__c> getEList(){
        ermList = [Select Id, Name, Model_Approach__c, Detailed_Structural_Stochastic_Model__c, FM_Specific_Risks__c, ERM_Risks__c, ERM_to_FM__c, Explanation__c, Residual_Standard_Deviation__c, Risk__c, Risk__r.Name, Simple_Stochastic_Model__c, ERM_Program_Identified_Risks__c From ERM_to_FM_Risk__c 
        			where ERM_to_FM__r.id =:ermID  ORDER BY Risk__r.Name NULLS LAST];
        return ermList;        
    }
    
    public pageReference saveChanges(){
     	update ermList;
        PageReference pageRef = new PageReference('/apex/ReconciliationMemo?id='+ermID);
        return pageRef;
    }
    
    public pageReference saveNewRF(){
        insert newRiskFactor;
        addRiskFactor.ERM_to_FM__c = ermID;
        addRiskFactor.Risk__c = newRiskFactor.id;
        insert addRiskFactor;
        newRiskFactor = new MLN_Risk__c();
        addRiskFactor = new ERM_to_FM_Risk__c();
        return null;
    }
    
    public pageReference addNewRF(){
        addRiskFactor.ERM_to_FM__c = ermID;
        insert addRiskFactor;        
        addRiskFactor = new ERM_to_FM_Risk__c();
        return null;
    }
    
    public string selectedRFId {get; set;}
    
    public void DeleteRiskFactor()
    {
        ERM_to_FM_Risk__c del = new ERM_to_FM_Risk__c(ID=selectedRFId);
        delete del;
    }   

}