src/objects/General_Ledger__c.object
<CustomObject>
    <label>General Ledger</label>
    <nameField>
        <label>General Ledger Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <label>Incident&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incidents_GL_Association__c.object
<CustomObject>
    <fields>
        <fullName>General_Ledger__c</fullName>
        <label>General Ledger</label>
        <referenceTo>General_Ledger__c</referenceTo>
        <relationshipLabel>Associated Incidents</relationshipLabel>
        <relationshipName>Incidents_GL_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Associated General Ledgers</relationshipLabel>
        <relationshipName>Incidents_GL_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Incidents/GL Association</label>
    <nameField>
        <displayFormat>IG{00000}</displayFormat>
        <label>Incidents/GL Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents/GL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Incidents_Association__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Incidents_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Incidents</relationshipLabel>
        <relationshipName>Risk_Incidents_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Incidents Association</label>
    <nameField>
        <displayFormat>RI{00000}</displayFormat>
        <label>Risk/Incidents Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Incidents Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IncidentsAssociationJSONToolkitTest.cls
@isTest
public class IncidentsAssociationJSONToolkitTest {
  
  static final String GLS_CONST = 'Test GLs';
  static final String RISK_CONST = 'Test Risk';
 
  
  static String JSONResult;
  
  
  static {
    Incident__c incident = new Incident__c(Name = 'Test');
      insert incident;
     
      Risk__c risk = new Risk__c(Name = RISK_CONST);
      insert risk;
      Risk_Incidents_Association__c riskIncidentsAssociation = new Risk_Incidents_Association__c(Incident__c = incident.Id, Risk__c = risk.Id);
      insert riskIncidentsAssociation;
      
      General_Ledger__c gls = new General_Ledger__c (Name = GLS_CONST);
      insert gls;
      Incidents_GL_Association__c incidentGlAssociation = new Incidents_GL_Association__c(Incident__c = incident.id, General_Ledger__c = gls.id);
      insert incidentGlAssociation;
      
      
      JSONResult = IncidentsAssociationJSONToolkit.toJSON(incident.Id);  
      }
      
      
 static testMethod void testIncident() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String riskName = parser.getText();
    //System.assert(riskName == RISK_CONST);
  } 
            
}