src/objects/General_Ledger__c.object
<CustomObject>
    <label>General Ledger</label>
    <nameField>
        <label>General Ledger Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incident__c.object
<CustomObject>
    <label>Incident</label>
    <nameField>
        <label>Incident&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incidents_GL_Association__c.object
<CustomObject>
    <fields>
        <fullName>General_Ledger__c</fullName>
        <label>General Ledger</label>
        <referenceTo>General_Ledger__c</referenceTo>
        <relationshipLabel>Associated Incidents</relationshipLabel>
        <relationshipName>Incidents_GL_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Associated General Ledgers</relationshipLabel>
        <relationshipName>Incidents_GL_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Incidents/GL Association</label>
    <nameField>
        <displayFormat>IG{00000}</displayFormat>
        <label>Incidents/GL Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents/GL Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_Incidents_Association__c.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <label>Incident</label>
        <referenceTo>Incident__c</referenceTo>
        <relationshipLabel>Associated Risks</relationshipLabel>
        <relationshipName>Risk_Incidents_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Associated Incidents</relationshipLabel>
        <relationshipName>Risk_Incidents_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk/Incidents Association</label>
    <nameField>
        <displayFormat>RI{00000}</displayFormat>
        <label>Risk/Incidents Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk/Incidents Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IncidentsAssociationJSONToolkit.cls
global class IncidentsAssociationJSONToolkit {
    webservice static String toJSON(String incidentsID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        
        categoryNames.add('GLs');
        categoryNames.add('Risks');
        
        List<Incidents_GL_Association__c> gls = [SELECT Incident__r.Id, Incident__r.Name, General_Ledger__r.Id, General_Ledger__r.Name from Incidents_GL_Association__c where Incident__r.Id =:incidentsID];
        List<Risk_Incidents_Association__c> risks = [SELECT Risk__r.Id, Risk__r.Name, Incident__r.Id, Incident__r.Name from Risk_Incidents_Association__c where Incident__r.Id =:incidentsID];


        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'INCIDENTS');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                           
                           if (categoryName == 'GLs')
                            {
                                for (Incidents_GL_Association__c gl : gls)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', gl.General_Ledger__r.Name);
                                        generator.writeStringField('objectID', gl.General_Ledger__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                           
                            else if (categoryName == 'Risks')
                            {
                                for (Risk_Incidents_Association__c risk : risks)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', risk.Risk__r.Name);
                                        generator.writeStringField('objectID', risk.Risk__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                         generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}