src/objects/HeatMapSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>HeatMapDimensions__c</fullName>
        <description>Enter a 1 or 2 digit number to represent the number of cells on both the x and y axes of the Heat Map. The default value is 5. Supported values are 3, 5 and 10. If an unsupported value is used, the Heat Map will revert to 5x5.</description>
        <label>HeatMapDimensions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HeatMapSettings</label>
</CustomObject>

src/classes/HeatmapFullController.cls
public class HeatmapFullController {

    public String heatmapPageName {get; set;}
    
    public Decimal heatmapDimensions {get; set;}

    public HeatmapFullController() {
        heatmapDimensions = HeatMapSettings__c.getInstance().HeatMapDimensions__c;
        if (heatmapDimensions == 3) {
            heatmapPageName = 'HeatMap3x3';
        } else if (heatmapDimensions == 10) {
            heatmapPageName = 'HeatMap10x10';            
        } else {
            heatmapPageName = 'HeatMap5x5';            
        }
    }
}