src/objects/Key_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Select the category for this key objective</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Balance Sheet and Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earnings and Margins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth and Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reputation, Compliance and Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Describe this KPI</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Measured_Unit__c</fullName>
        <inlineHelpText>Select the unit used for measurement</inlineHelpText>
        <label>Measured Unit</label>
        <picklist>
            <picklistValues>
                <fullName>AED Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratio%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Key Objective</label>
    <nameField>
        <label>Key Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quarterly_Measure__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Enter the evaluation date</inlineHelpText>
        <label>Evaluation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Objective__c</fullName>
        <label>Key Objective</label>
        <referenceTo>Key_Objective__c</referenceTo>
        <relationshipLabel>Quarterly Measures</relationshipLabel>
        <relationshipName>Quarterly_Measures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quarterly_Goal__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter the goal for this quarter for this key objective</inlineHelpText>
        <label>Quarterly Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarterly_Measure__c</fullName>
        <inlineHelpText>Enter the value measured</inlineHelpText>
        <label>Quarterly Measure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quarterly Measure</label>
    <nameField>
        <displayFormat>QM-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quarterly Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuarterlyMeasureChartControllerTest.cls
@isTest
public class QuarterlyMeasureChartControllerTest{
    public static testmethod  void runTest(){
        Key_Objective__c key = new Key_Objective__c(Name='Test Key',Category__c = 'Balance Sheet and Capital',Description__c = 'Test',Measured_Unit__c = 'Ratio%');
        insert key;
        List<Quarterly_Measure__c> qmList = new List<Quarterly_Measure__c>();
        Quarterly_Measure__c qm = new Quarterly_Measure__c(Key_Objective__c = key.id,Evaluation_Date__c = system.today().addDays(5),Quarterly_Goal__c = 1000,Quarterly_Measure__c = 100);
        qmList.add(qm);
        Quarterly_Measure__c qm1 = new Quarterly_Measure__c(Key_Objective__c = key.id,Evaluation_Date__c = system.today().addDays(5),Quarterly_Goal__c = null,Quarterly_Measure__c = 100);
        qmList.add(qm1);
        insert qmList;
        ApexPages.StandardController sc = new ApexPages.StandardController (key);
        QuarterlyMeasureChartController QMCC = new QuarterlyMeasureChartController(sc);
    }
}