src/objects/Key_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Measured_Unit__c</fullName>
        <inlineHelpText>Select the unit used for measurement</inlineHelpText>
        <label>Measured Unit</label>
        <picklist>
            <picklistValues>
                <fullName>AED Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratio%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Key Objective</label>
    <nameField>
        <label>Key Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quarterly_Measure__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Enter the evaluation date</inlineHelpText>
        <label>Evaluation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Objective__c</fullName>
        <label>Key Objective</label>
        <referenceTo>Key_Objective__c</referenceTo>
        <relationshipLabel>Quarterly Measures</relationshipLabel>
        <relationshipName>Quarterly_Measures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quarterly_Goal__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter the goal for this quarter for this key objective</inlineHelpText>
        <label>Quarterly Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarterly_Measure__c</fullName>
        <inlineHelpText>Enter the value measured</inlineHelpText>
        <label>Quarterly Measure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quarterly Measure</label>
    <nameField>
        <displayFormat>QM-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quarterly Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuarterlyMeasureChartController.cls
public class QuarterlyMeasureChartController{
  
    public List<String> chartData {get; set;}
    
    public QuarterlyMeasureChartController(ApexPages.StandardController stdController){
        Key_Objective__c ko = (Key_Objective__c)stdController.getRecord();
        
        chartData = new List<String>();
        
        Integer currentYear = date.today().year();
        Integer previousYear = date.today().year()-1;
        
        for(Quarterly_Measure__c r:[select id, Key_Objective__r.Measured_Unit__c,Quarterly_Goal__c, Name, Evaluation_Date__c, Key_Objective__c, Quarterly_Measure__c from Quarterly_Measure__c where Key_Objective__c =: ko.id AND (CALENDAR_YEAR(Evaluation_Date__c) =: currentYear OR CALENDAR_YEAR(Evaluation_Date__c) =: previousYear) order by Evaluation_Date__c]){
            string dateFormat = string.valueOf(r.Evaluation_Date__c.format());
            
            List<string> dateFormatSplit = dateFormat.split('00:');
            
            if(r.Quarterly_Goal__c == null){
                r.Quarterly_Goal__c = 0;   
            }
            
            if(r.Key_Objective__r.Measured_Unit__c == 'Ratio%'){
                r.Quarterly_Goal__c /= 100;
                r.Quarterly_Measure__c /= 100;
            }
            
            string data = ',["' + dateFormatSplit[0] + '", ' + r.Quarterly_Measure__c + ',' + r.Quarterly_Goal__c + ']';
            chartData.add(data);
        }
        
    }

}