src/objects/Key_Risk_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Key_Risk_Metric_Measure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Risk Metric Measure</label>
        <referenceTo>Key_Risk_Metric_Measure__c</referenceTo>
        <relationshipLabel>Key Risk Metrics</relationshipLabel>
        <relationshipName>Key_Risk_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Measured_Unit__c</fullName>
        <label>Measured Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Ratio%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AED Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD Dollars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Key Risk Metric</label>
    <nameField>
        <label>Key Risk Metric</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Risk Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Key_Risk_Metric_Measure__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <label>Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Evaluation_Date__c</fullName>
        <label>Evaluation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Risk_Metric__c</fullName>
        <label>Key Risk Metric</label>
        <referenceTo>Key_Risk_Metric__c</referenceTo>
        <relationshipLabel>Key Risk Metric Measures</relationshipLabel>
        <relationshipName>Key_Risk_Metric_Measures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lower_Limit__c</fullName>
        <label>Lower Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upper_Limit__c</fullName>
        <label>Upper Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD__c</fullName>
        <label>YTD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Key Risk Metric Measure</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Risk Metric Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KeyRiskMeasureChartController.cls
public with sharing class KeyRiskMeasureChartController {
  public List<String> chartData {get; set;}
    
    public KeyRiskMeasureChartController(ApexPages.StandardController stdController){
        Key_Risk_Metric__c krm = (Key_Risk_Metric__c)stdController.getRecord();
        chartData = new List<String>();
        Integer currentYear = date.today().year();
        
        for(Key_Risk_Metric_Measure__c r : [Select Upper_Limit__c, Lower_Limit__c, Actual__c, YTD__c, Key_Risk_Metric__r.Measured_Unit__c, Key_Risk_Metric__c, Id, Evaluation_Date__c From Key_Risk_Metric_Measure__c k where Key_Risk_Metric__c =: krm.id AND CALENDAR_YEAR(Evaluation_Date__c) =: currentYear order by Evaluation_Date__c]){
            string dateFormat = string.valueOf(r.Evaluation_Date__c.format());
            List<string> dateFormatSplit = dateFormat.split('00:');
            
          if(r.Upper_Limit__c == null) r.Upper_Limit__c = 0;
            if(r.Lower_Limit__c == null) r.Lower_Limit__c = 0;
            if(r.Actual__c == null) r.Actual__c = 0;
            if(r.YTD__c == null) r.YTD__c = 0;
            
            if(r.Key_Risk_Metric__r.Measured_Unit__c == 'Ratio%'){
              r.Lower_Limit__c /= 100;
                r.Upper_Limit__c /= 100;
                r.Actual__c /= 100;
                r.YTD__c /= 100;
            }
            
            string cdata = ',["' + dateFormatSplit[0] + '", ' + r.Upper_Limit__c + ',' + r.Actual__c + ','+ r.YTD__c+ ','+ r.Lower_Limit__c + ']';
            chartData.add(cdata);
        }
    }
}