src/objects/MLN_Risk__c.object
<CustomObject>
    <description>MillimanGRC Risk Custom Object</description>
    <fields>
        <fullName>Quarterly_Review_Status_Track__c</fullName>
        <description>This field is used to track the changes to Quarterly Review Status value</description>
        <label>Quarterly Review Status Track</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarterly_Review_Status__c</fullName>
        <label>Quarterly Review Status</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed but no changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed with changes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateQuaterlyReviewStatus.cls
public class UpdateQuaterlyReviewStatus {
    String status;
    String riskId;
    public UpdateQuaterlyReviewStatus(){
        riskId = ApexPages.currentPage().getParameters().get('id');
        status= ApexPages.currentPage().getParameters().get('status');        
    }
     public PageReference updateStatus(){ 
         if(riskId != null && status != null){
            MLN_Risk__c risk = [SELECT Id,Quarterly_Review_Status__c,Quarterly_Review_Status_Track__c FROM MLN_Risk__c WHERE Id=:riskId];
            risk.Quarterly_Review_Status__c = status;
            risk.Quarterly_Review_Status_Track__c = status + ' '+system.now().format('MM/dd/yyyy HH:mm:ss');
            update risk;
            return new PageReference('/'+riskId);
         }
         return null;
     }
}