src/objects/Process__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process/Vendor Location Associations</relationshipLabel>
        <relationshipName>Process_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Process/Vendor Location Associations</relationshipLabel>
        <relationshipName>Process_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRCVLA{000000}</displayFormat>
        <label>Process/Vendor Location Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRDVLA{000000}</displayFormat>
        <label>Product/Vendor Location Association Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Location__c.object
<CustomObject>
    <label>Vendor Location</label>
    <nameField>
        <label>Vendor Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VendorLocationAssociationJSONToolkit.cls
global class VendorLocationAssociationJSONToolkit {
    webservice static String toJSON(String vendorLocationID)
    {
        //List<sObject> returnedAssociations = Database.query(query);
        
        List<String> categoryNames = new List<String>();
        
       
        categoryNames.add('Processes');
        categoryNames.add('Products');

        List<Process_Vendor_Location_Association__c> processes = [SELECT Vendor_Location__r.Id, Vendor_Location__r.Name, Process__r.Id, Process__r.Name from Process_Vendor_Location_Association__c where Vendor_Location__r.Id =:vendorLocationID];
        List<Product_Vendor_Location_Association__c> products = [SELECT Vendor_Location__r.Id, Vendor_Location__r.Name, Product__r.Id, Product__r.Name from Product_Vendor_Location_Association__c where Vendor_Location__r.Id =:vendorLocationID];
        

        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject();
            generator.writeStringField('name', 'VENDOR LOCATIONS');
            generator.writeStringField('noLink', 'TRUE');
            generator.writeFieldName('children');
            generator.writeStartArray();
                for (String categoryName : categoryNames)
                {
                    generator.writeStartObject();
                        generator.writeStringField('name', categoryName);
                        generator.writeStringField('noLink', 'TRUE');
                        generator.writeFieldName('children');
                        generator.writeStartArray();
                           
                         
                         if (categoryName == 'Processes')
                            {
                                for (Process_Vendor_Location_Association__c process : processes)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', process.Process__r.Name);
                                        generator.writeStringField('objectID', process.Process__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                            else if (categoryName == 'Products')
                            {
                                for (Product_Vendor_Location_Association__c product : products)
                                {
                                    generator.writeStartObject();
                                        generator.writeStringField('name', product.Product__r.Name);
                                        generator.writeStringField('objectID', product.Product__r.ID);
                                    generator.writeEndObject();
                                }
                            }
                           
                         generator.writeEndArray();
                    generator.writeEndObject();
                }
            generator.writeEndArray();
        generator.writeEndObject();
        
        String returnString = generator.getAsString();
        returnString = returnString.replace('\\"', '"');
        returnString = returnString.replace('"{', '{');
        returnString = returnString.replace('}"', '}');
        
        return returnString;
    }
}