src/objects/Process__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process/Vendor Location Associations</relationshipLabel>
        <relationshipName>Process_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Process/Vendor Location Associations</relationshipLabel>
        <relationshipName>Process_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRCVLA{000000}</displayFormat>
        <label>Process/Vendor Location Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Vendor_Location_Association__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Location__c</fullName>
        <label>Vendor Location</label>
        <referenceTo>Vendor_Location__c</referenceTo>
        <relationshipLabel>Product/Vendor Location Associations</relationshipLabel>
        <relationshipName>Product_Vendor_Location_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product/Vendor Location Association</label>
    <nameField>
        <displayFormat>PRDVLA{000000}</displayFormat>
        <label>Product/Vendor Location Association Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product/Vendor Location Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Location__c.object
<CustomObject>
    <label>Vendor Location</label>
    <nameField>
        <label>Vendor Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VendorLocationAssociationJSONToolkitTest.cls
@isTest
public class VendorLocationAssociationJSONToolkitTest {
  static final String VENDOR_LOCATION_CONST = 'Test Vendor Location';
  static final String PROCESS_CONST = 'Test Process';
  static final String PRODUCT_CONST = 'Test Product';
  
  
  static String JSONResult;
  
  static {
    Vendor_Location__c vendorLocation = new Vendor_Location__c(Name = 'Test');
      insert vendorLocation;
       
      Process__c processes = new Process__c(Name = PROCESS_CONST);
      insert processes;
      Process_Vendor_Location_Association__c processVendorLocationAssociation = new Process_Vendor_Location_Association__c(Vendor_Location__c = vendorLocation.Id, Process__c = processes.Id);
      insert processVendorLocationAssociation;
      
     Product__c product = new Product__c(Name = 'Test Product');
      insert product;
      Product_Vendor_Location_Association__c productVendorLocationAssociation = new Product_Vendor_Location_Association__c(Vendor_Location__c = vendorLocation.id, Product__c = product.id);
      insert productVendorLocationAssociation;
      
      JSONResult = VendorLocationAssociationJSONToolkit.toJSON(vendorLocation.Id);  
      }
      
      
 static testMethod void testVendorLocation() {
    Integer i = 0;
    JSONParser parser = JSON.createParser(JSONResult);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'name') {
        i++;
        if (i == 3) {
          parser.nextToken();
          break;
        }
      }
    }

    String processName = parser.getText();
    System.assert(processName == PROCESS_CONST);
  } 
}