src/objects/Process__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UGI_Process__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Operational &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>UGI_Risk__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>UGI Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <recordTypes>
        <fullName>IA</fullName>
        <active>true</active>
        <label>IA</label>
    </recordTypes>
    <recordTypes>
        <fullName>SOX</fullName>
        <active>true</active>
        <label>SOX</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UGI_Subsidiary__c.object
<CustomObject>
    <fields>
        <fullName>AmeriGas__c</fullName>
        <label>AmeriGas</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Antargaz_Finagaz__c</fullName>
        <label>Antargaz/Finagaz</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Avantigas__c</fullName>
        <label>Avantigas</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Degree_of_Centralization__c</fullName>
        <label>Degree of Centralization</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Degree_of_Process_or_Systems_Change__c</fullName>
        <label>Degree of Process or Systems Change</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extent_of_Automation__c</fullName>
        <label>Extent of Automation</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extent_of_External_Party_Involvement__c</fullName>
        <label>Extent of External Party Involvement</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flaga__c</fullName>
        <label>Flaga</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>History_of_Deficiencies__c</fullName>
        <label>History of Deficiencies</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Holding_Company__c</fullName>
        <label>Holding Company</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Overall_Complexity__c</fullName>
        <label>Overall Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Overall_Risk_Score__c</fullName>
        <label>Overall Risk Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>UGI_Process__c</referenceTo>
        <relationshipName>Subsidiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Adequacy__c</fullName>
        <label>System Adequacy</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Volume__c</fullName>
        <label>Transaction Volume</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UGI_Energy_Services__c</fullName>
        <label>UGI Energy Services</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UGI_Utilities__c</fullName>
        <label>UGI Utilities</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>UGI Subsidiary</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Process_Edit_Controller.cls
public class Process_Edit_Controller {
    public UGI_Process__c process{get;set;}
    public list<ProcessWrapper> processWrapperList{get;set;}
    public integer count;
    public integer deleteIdx{get;set;}
    list<UGI_Subsidiary__c> dataToDelete;
    list<UGI_Subsidiary__c> subsidiaries;
    
    string retURL;
    public boolean isSOX{get;set;}
    
    public Process_Edit_Controller(ApexPages.StandardController std){
        count = 0;
        process = [select id, Name, Name__c, Risk__c, Source__c, Category__c, RecordTypeId from UGI_Process__c where id =: std.getRecord().Id];
        system.debug('#### ID : '+process.Id);
        
        string type;
        if(process.RecordTypeId == '012M00000000m0H'){
            isSOX = true;
            type = 'SOX';
        }else{
            isSOX = false;
            type = 'IA';
        }
        
        //subsidiaries = new list<UGI_Subsidiary__c>();
        subsidiaries = [select id, Name, Process__c, Overall_Complexity__c, Degree_of_Centralization__c, Extent_of_Automation__c, Transaction_Volume__c, 
                        History_of_Deficiencies__c, Degree_of_Process_or_Systems_Change__c, Extent_of_External_Party_Involvement__c, System_Adequacy__c, Overall_Risk_Score__c, 
                        AmeriGas__c, Antargaz_Finagaz__c, Avantigas__c, Flaga__c, Holding_Company__c, UGI_Energy_Services__c, UGI_Utilities__c 
                        from UGI_Subsidiary__c where Process__c =: process.Id and Type__c =: type order by Name];
        system.debug('#### subsidiaries : '+subsidiaries);
        
        processWrapperList = new list<ProcessWrapper>();
        for(UGI_Subsidiary__c s : subsidiaries){
            ProcessWrapper pw = new ProcessWrapper(s,count++);
            processWrapperList.add(pw);
        }
        processWrapperList.add(new ProcessWrapper(count++));
        system.debug('#### processWrapperList : '+processWrapperList);
        dataToDelete = new list<UGI_Subsidiary__c>();
        retURL = apexPages.currentPage().getParameters().get('retURL');
    }
    
    public PageReference save(){
        update process;
        saveSubsidiary();
        PageReference pg = new PageReference('/'+process.Id);
        return pg;
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference(retURL);
        return pg;
    }
    
    public void saveSubsidiary(){
        list<UGI_Subsidiary__c> dataToUpsert = new list<UGI_Subsidiary__c>();
        for(ProcessWrapper pw : processWrapperList){
            if(pw.subsidiary.Name != null && pw.subsidiary.Name != ''){
                if(pw.subsidiary.Process__c == null){
                    pw.subsidiary.Process__c = process.Id;
                }
                if(process.RecordTypeId == '012M00000000m0H'){
                    pw.subsidiary.Type__c = 'SOX';
                }else{
                    pw.subsidiary.Type__c = 'IA';
                }
                dataToUpsert.add(pw.subsidiary);
            }
        }
        system.debug('#### data To Upsert : '+dataToUpsert);
        try{
            if(dataToDelete.size() > 0){
                delete dataToDelete;
            }
            if(dataToUpsert.size() > 0){
                upsert dataToUpsert;
                subsidiaries = [select id, Name, Process__c, Overall_Complexity__c, Degree_of_Centralization__c, Extent_of_Automation__c, Transaction_Volume__c, 
                                History_of_Deficiencies__c, Degree_of_Process_or_Systems_Change__c, Extent_of_External_Party_Involvement__c, System_Adequacy__c, Overall_Risk_Score__c
                                from UGI_Subsidiary__c where Process__c =: process.Id and Type__c = 'SOX'];
                system.debug('#### subsidiaries : '+subsidiaries);
                count = 0;
                processWrapperList = new list<ProcessWrapper>();
                for(UGI_Subsidiary__c s : subsidiaries){
                    ProcessWrapper pw = new ProcessWrapper(s,count++);
                    processWrapperList.add(pw);
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Function cannot be left blank.'));
            }
        }catch(Exception exp){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'ERROR: '+exp.getMessage()));
        }
    }
    
    public void addSubsidiary(){
        processWrapperList.add(new ProcessWrapper(count++));
    }
    
    public void removeSubsidiary(){
        system.debug('#### deleteIdx : '+deleteIdx );
        ProcessWrapper delW = processWrapperList.get(deleteIdx);
        if(delW.subsidiary.Process__c != null){
            dataToDelete.add(delW.subsidiary);
        }
        processWrapperList.remove(deleteIdx);
        count = 0;
        for(ProcessWrapper pw : processWrapperList){
            pw.index = count++;
        }
    }
    
    public class ProcessWrapper{
        public boolean selected{get;set;}
        public integer index{get;set;}
        public UGI_Subsidiary__c subsidiary{get;set;}
        public ProcessWrapper(UGI_Subsidiary__c subsidiary, integer index){
            this.subsidiary = subsidiary;
            this.index = index;
            this.selected = false;
        }
        public ProcessWrapper(integer index){
            subsidiary = new UGI_Subsidiary__c();
            this.index = index;
            this.selected = false;
        }
    }
}