src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_History__c.object
<CustomObject>
    <description>Keeps Risk history for impact and likelihood values.</description>
    <fields>
        <fullName>Expected_Current_Impact_New__c</fullName>
        <label>Expected Current Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Current_Likelihood_New__c</fullName>
        <label>Expected Current Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Impact_New__c</fullName>
        <label>Expected Inherent Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Likelihood_New__c</fullName>
        <label>Expected Inherent Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Impact_New__c</fullName>
        <label>Expected Target Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Likelihood_New__c</fullName>
        <label>Expected Target Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Risk History</relationshipLabel>
        <relationshipName>Risk_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valuation_Date__c</fullName>
        <label>Valuation Date</label>
        <type>Date</type>
    </fields>
    <label>Risk History</label>
    <nameField>
        <displayFormat>RH-{0000}</displayFormat>
        <label>Risk History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RiskHistoryComponentController.cls
public class RiskHistoryComponentController {
 
    public class objectHistoryLine {
        public Date valuationDate {get; set;}
        public Decimal currentRiskScore {get; set;}
        public Decimal currentRiskScoreInherent {get; set;}
        public Decimal currentRiskScoreTarget {get; set;}                
    }
        
    // External variables
    public static SObject myObject {get; set;}
    public Integer listSize {get; set;}
    
    public objectHistoryLine[] getCustomHistory () {
        Id riskId = String.valueOf(myObject.get('Id'));
        List<Risk_History__c> rhList = [Select   Expected_Current_Impact_New__c, 
                                                 Expected_Current_Likelihood_New__c,
                                                 Expected_Inherent_Impact_New__c,
                                                 Expected_Inherent_Likelihood_New__c,
                                                 Expected_Target_Impact_New__c,
                                                 Expected_Target_Likelihood_New__c,
                                                 Valuation_Date__c,
                                                 Risk__c
                                        From     Risk_History__c
                                        Where    Risk__c =: riskId  
                                        And      Valuation_Date__c >= LAST_N_YEARS:5
                                        Order By Valuation_Date__c];
        
        List<objectHistoryLine> ohl = new List<objectHistoryLine>();   
        listSize = rhList.size();
        
        if (rhList.size() > 0) { 
            for (Risk_History__c h: rhList) {
                objectHistoryLine h1 = new objectHistoryLine();
                h1.valuationDate = h.Valuation_Date__c;
                if (h.Expected_Current_Impact_New__c != null && h.Expected_Current_Likelihood_New__c != null) {
                    h1.currentRiskScore = h.Expected_Current_Impact_New__c * h.Expected_Current_Likelihood_New__c;}
                else h1.currentRiskScore = 0;
                if (h.Expected_Inherent_Impact_New__c != null && h.Expected_Inherent_Likelihood_New__c != null) {    
                    h1.currentRiskScoreInherent = h.Expected_Inherent_Impact_New__c * h.Expected_Inherent_Likelihood_New__c;}
                else h1.currentRiskScoreInherent = 0;
                if (h.Expected_Target_Impact_New__c != null && h.Expected_Target_Likelihood_New__c != null) {   
                    h1.currentRiskScoreTarget = h.Expected_Target_Impact_New__c * h.Expected_Target_Likelihood_New__c;}
                else h1.currentRiskScoreTarget = 0;
                ohl.add(h1);
            }
        }
        else {
            objectHistoryLine h1 = new objectHistoryLine();
            h1.currentRiskScore = 0;
            h1.currentRiskScoreInherent = 0;
            h1.currentRiskScoreTarget = 0;
            ohl.add(h1);
        }
/*
        for (Risk_History__c h: rhList) {
            if (h.Expected_Inherent_Impact_New__c != null && h.Expected_Inherent_Likelihood_New__c != null) {
                objectHistoryLine h1 = new objectHistoryLine();
                h1.valuationDate = h.Valuation_Date__c;
                h1.currentRiskScoreInherent = h.Expected_Inherent_Impact_New__c * h.Expected_Inherent_Likelihood_New__c;
                ohl.add(h1);
            }
        }

        for (Risk_History__c h: rhList) {
            if (h.Expected_Target_Impact_New__c != null && h.Expected_Target_Likelihood_New__c != null) {
                objectHistoryLine h1 = new objectHistoryLine();
                h1.valuationDate = h.Valuation_Date__c;
                h1.currentRiskScoreTarget = h.Expected_Target_Impact_New__c * h.Expected_Target_Likelihood_New__c;
                ohl.add(h1);
            }
        }
*/
        return ohl;   
    }
}