src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <fields>
        <fullName>Last_Date_Risk_Assessed__c</fullName>
        <description>date on which this Risk was last Assessed</description>
        <inlineHelpText>Enter the date when last assessed</inlineHelpText>
        <label>Last Date Risk Assessed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Risk_Description__c</fullName>
        <description>Description of the risk event.</description>
        <inlineHelpText>Enter a description of the risks sufficient to provide the reader with a clear understanding of the scope of the risk.  Limited to 100 characters - more detail can be added in Risk Detail</inlineHelpText>
        <label>Risk Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who has responsibility for this risk. This person will determine the current risk level.</description>
        <inlineHelpText>Select the appropriate Risk Owner from the list provided. Must be in Contacts. Only a single Risk Owner can be selected.</inlineHelpText>
        <label>Risk Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RiskUpdateFlowController.cls
public class RiskUpdateFlowController{

    public RiskUpdateFlowController(ApexPages.StandardController controller){}
    private final Risk__c risk {get;set;}
    public Flow.Interview.Risk_Update myflow {get;set;}


    String Id;
    public RiskUpdateFlowController(){
        Id=Apexpages.currentPage().getParameters().get('id');
    }



    public class risksList {
        public String riskName {get; set;}
        public Date lastAssessed {get; set;}
        public String riskDescription {get; set;}
		
		public risksList() {
			
		}
		
    }
    
    // External variables
    public SObject myObject {get; set;}
    
    public risksList[] getRisks () {
	
		List<Risk__c> rList;
		if (myflow != null) {
	        rList= [SELECT Id, Risk_Owner__c, Name, Last_Date_Risk_Assessed__c, Risk_Description__c
	        from Risk__c where Risk_Owner__c =: myflow.varContactId ];
		} else {
			rList = new List<Risk__c>();
		}
       
        
        List<risksList> rL = new List<risksList>();   
        
        if (rList.size() > 0) { 
            for (Risk__c r: rList) {
                risksList r1 = new risksList();
                r1.riskName = r.Name;
                r1.lastAssessed = r.Last_Date_Risk_Assessed__c;
                r1.riskDescription = r.Risk_Description__c;
                rL.add(r1);
            }
        }
        else {
            risksList r1 = new risksList();
            r1.riskName = 'No Risks';
            //r1.lastAssessed = 0;
            rL.add(r1);
        }

        return rL;   
    }

    public String getRender(){ 
        if (myflow == null)
    {
        return 'false' ;
    }
    else
    { 
        return  myflow.varRender;
    }
    }


    public PageReference getEndPage() {

        PageReference pageRef = new Pagereference('http://www.riskonnect.com');

        return pageRef;
     }
}