src/objects/Risk__c.object
<CustomObject>
    <description>2012 ERM Risks</description>
    <fields>
        <fullName>Expected_Inherent_Impact__c</fullName>
        <description>The Expected Impact without controls. If used as part of a Triangular Distribution is intended to be the most common value, if part of a Normal Distribution, is to be the mean of that distribution</description>
        <inlineHelpText>Select the expected value. This value is as if no Controls will work.
0 = No impact, default value
1 = Minimal - Less than $100,000 per event
2 = Between $100K and $1M
3 = Between $1M and $10M
4 = Between $10M and $100M
5 = Greater than $100M</inlineHelpText>
        <label>Expected Inherent Impact</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Likelihood__c</fullName>
        <description>The Likelihood the risk event will occur assuming no controls will work or are in existence.
 If used as part of a Triangular Distribution is intended to be the most common value, if part of a Normal Distribution, is to be the mean of that distribution</description>
        <inlineHelpText>Select the expected value. This value is as if no Controls will work. 
1 = Rare &gt;1:100 Years
2 = Once in 100 years
3 = Once in 10 years
4 = Once a year 
5 = Frequent - 10 times a year</inlineHelpText>
        <label>Expected Inherent Likelihood</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Residual_or_Current_Impact__c</fullName>
        <description>The Expected Impact with the current controls, assuming they all work as expected.. If used as part of a Triangular Distribution is intended to be the most common value, if part of a Normal Distribution, is to be the mean of that distribution</description>
        <inlineHelpText>Enter the appropriate value - Assume existing Controls will work as expected.
0 = No impact, default
1 = Minimal - Less than $100,000 per event
2 = Between $100K and $1M
3 = Between $1M and $10M
4 = Between $10M and $100M
5 = Greater than $100M</inlineHelpText>
        <label>Expected Residual or Current Impact</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Residual_or_Current_Likelihood__c</fullName>
        <description>The current Likelihood that the risk event will occur, assuming all current controls work as expected.</description>
        <inlineHelpText>Enter the appropriate value - Assume existing Controls will work as expected.
0 = Never, default value
1 = Rare &gt;1:100 Years
2 = Once in 100 years
3 = Once in 10 years
4 = Once a year 
5 = Frequent - 10 times a year</inlineHelpText>
        <label>Expected Residual or Current Likelihood</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Impact__c</fullName>
        <description>The desired or preferred Impact level, should the risk event occur. may be higher or lower than Current Likelihood.</description>
        <inlineHelpText>Select the expected value. This is the Risk Level that should exist.
0 = No impact, default value
1 = Minimal - Less than $100,000 per event
2 = Between $100K and $1M
3 = Between $1M and $10M
4 = Between $10M and $100M
5 = Greater than $100M</inlineHelpText>
        <label>Expected Target Impact</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Likelihood__c</fullName>
        <description>The most acceptable Likelihood of the Risk event occurring.</description>
        <inlineHelpText>Select the expected value. This is the Risk Level that should exist.
0 = Never, default value
1 = Rare &gt;1:100 Years
2 = Once in 100 years
3 = Once in 10 years
4 = Once a year 
5 = Frequent - 10 times a year</inlineHelpText>
        <label>Expected Target Likelihood</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>2012 ERM Risks</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>2012 ERM Risks</pluralLabel>
    <recordTypes>
        <fullName>Expected</fullName>
        <active>true</active>
        <label>Risk - Expected</label>
    </recordTypes>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risk_History__c.object
<CustomObject>
    <description>Keeps Risk history for impact and likelihood values.</description>
    <fields>
        <fullName>Change_Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Current_Impact_New__c</fullName>
        <label>Expected Current Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Current_Impact_Old__c</fullName>
        <label>Expected Current Impact (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Current_Likelihood_New__c</fullName>
        <label>Expected Current Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Current_Likelihood_Old__c</fullName>
        <label>Expected Current Likelihood (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Impact_New__c</fullName>
        <label>Expected Inherent Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Impact_Old__c</fullName>
        <label>Expected Inherent Impact (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Likelihood_New__c</fullName>
        <label>Expected Inherent Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inherent_Likelihood_Old__c</fullName>
        <label>Expected Inherent Likelihood (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Impact_New__c</fullName>
        <label>Expected Target Impact (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Impact_Old__c</fullName>
        <label>Expected Target Impact (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Likelihood_New__c</fullName>
        <label>Expected Target Likelihood (New)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Target_Likelihood_Old__c</fullName>
        <label>Expected Target Likelihood (Old)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risk__c</referenceTo>
        <relationshipLabel>Risk History</relationshipLabel>
        <relationshipName>Risk_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk History</label>
    <nameField>
        <displayFormat>RH-{0000}</displayFormat>
        <label>Risk History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testRiskTriggers.cls
/*
 * JCM 2012/12/20
 * PST-00005647
 */
@isTest
public class testRiskTriggers
{
    @isTest
    static void testInsertandUpdate()
    {
        Risk__c risk = new Risk__c(
            Expected_Residual_or_Current_Impact__c='1',
            Expected_Residual_or_Current_Likelihood__c='1',
            Expected_Inherent_Impact__c='1',
            Expected_Inherent_Likelihood__c='1',
            Expected_Target_Impact__c='1',
            Expected_Target_Likelihood__c='1'
            );

        insert risk;

        List<Risk_History__c> histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Likelihood_New__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Likelihood_New__c,

            Expected_Current_Impact_Old__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Impact_Old__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        // Check for history record for initial insert.
        System.AssertEquals(1, histories.size(), 'Expected 1 history record, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            System.Assert(history.Change_Description__c.containsIgnoreCase('initial'));
            System.AssertEquals(1, history.Expected_Current_Impact_New__c);
            System.AssertEquals(1, history.Expected_Current_Likelihood_New__c);
            System.AssertEquals(1, history.Expected_Inherent_Impact_New__c);
            System.AssertEquals(1, history.Expected_Inherent_Likelihood_New__c);
            System.AssertEquals(1, history.Expected_Target_Impact_New__c);
            System.AssertEquals(1, history.Expected_Target_Likelihood_New__c);

            System.AssertEquals(1, history.Expected_Current_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Current_Likelihood_Old__c);
            System.AssertEquals(1, history.Expected_Inherent_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Inherent_Likelihood_Old__c);
            System.AssertEquals(1, history.Expected_Target_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Target_Likelihood_Old__c);
        }

        risk.Expected_Residual_or_Current_Impact__c = '5';
        risk.Expected_Residual_or_Current_Likelihood__c = '5';
        risk.Expected_Inherent_Impact__c = '5';
        risk.Expected_Inherent_Likelihood__c = '5';
        risk.Expected_Target_Impact__c = '5';
        risk.Expected_Target_Likelihood__c = '5';

        update risk;

        histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Impact_Old__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Impact_Old__c,
            Expected_Current_Likelihood_New__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Likelihood_New__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        Boolean foundChangeHistory = false;

        // Check for history record for updated values.
        System.AssertEquals(2, histories.size(), 'Expected 2 history records, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            if (history.Change_Description__c.containsIgnoreCase('change'))
            {
                System.AssertEquals(5, history.Expected_Current_Impact_New__c);
                System.AssertEquals(1, history.Expected_Current_Impact_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Impact_New__c);
                System.AssertEquals(1, history.Expected_Inherent_Impact_Old__c);
                System.AssertEquals(5, history.Expected_Target_Impact_New__c);
                System.AssertEquals(1, history.Expected_Target_Impact_Old__c);

                System.AssertEquals(5, history.Expected_Current_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Current_Likelihood_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Inherent_Likelihood_Old__c);
                System.AssertEquals(5, history.Expected_Target_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Target_Likelihood_Old__c);

                foundChangeHistory = true;
            }
        }

        System.Assert(foundChangeHistory, 'Did not find history record for change');
    }    

    @isTest
    static void testInsertandUpdateSomeUnchanged()
    {
        Risk__c risk = new Risk__c(
            Expected_Residual_or_Current_Impact__c='1',
            Expected_Residual_or_Current_Likelihood__c='1',
            Expected_Inherent_Impact__c='1',
            Expected_Inherent_Likelihood__c='1',
            Expected_Target_Impact__c='1',
            Expected_Target_Likelihood__c='1'
            );

        insert risk;

        List<Risk_History__c> histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Likelihood_New__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Likelihood_New__c,

            Expected_Current_Impact_Old__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Impact_Old__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        // Check for history record for initial insert.
        System.AssertEquals(1, histories.size(), 'Expected 1 history record, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            System.Assert(history.Change_Description__c.containsIgnoreCase('initial'));
            System.AssertEquals(1, history.Expected_Current_Impact_New__c);
            System.AssertEquals(1, history.Expected_Current_Likelihood_New__c);
            System.AssertEquals(1, history.Expected_Inherent_Impact_New__c);
            System.AssertEquals(1, history.Expected_Inherent_Likelihood_New__c);
            System.AssertEquals(1, history.Expected_Target_Impact_New__c);
            System.AssertEquals(1, history.Expected_Target_Likelihood_New__c);

            System.AssertEquals(1, history.Expected_Current_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Current_Likelihood_Old__c);
            System.AssertEquals(1, history.Expected_Inherent_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Inherent_Likelihood_Old__c);
            System.AssertEquals(1, history.Expected_Target_Impact_Old__c);
            System.AssertEquals(1, history.Expected_Target_Likelihood_Old__c);
        }

        risk.Expected_Residual_or_Current_Impact__c = '5';
        risk.Expected_Residual_or_Current_Likelihood__c = '5';
        risk.Expected_Inherent_Impact__c = '5';
        risk.Expected_Inherent_Likelihood__c = '5';

        // Leave some fields unchanged.
        //risk.Expected_Target_Impact__c = '5';
        //risk.Expected_Target_Likelihood__c = '5';

        update risk;

        histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Impact_Old__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Impact_Old__c,
            Expected_Current_Likelihood_New__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Likelihood_New__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        Boolean foundChangeHistory = false;

        // Check for history record for updated values.
        System.AssertEquals(2, histories.size(), 'Expected 2 history records, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            if (history.Change_Description__c.containsIgnoreCase('change'))
            {
                System.AssertEquals(5, history.Expected_Current_Impact_New__c);
                System.AssertEquals(1, history.Expected_Current_Impact_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Impact_New__c);
                System.AssertEquals(1, history.Expected_Inherent_Impact_Old__c);

                System.AssertEquals(5, history.Expected_Current_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Current_Likelihood_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Inherent_Likelihood_Old__c);

                // Check the unchanged values.
                System.AssertEquals(1, history.Expected_Target_Impact_New__c);
                System.AssertEquals(1, history.Expected_Target_Impact_Old__c);
                System.AssertEquals(1, history.Expected_Target_Likelihood_New__c);
                System.AssertEquals(1, history.Expected_Target_Likelihood_Old__c);

                foundChangeHistory = true;
            }
        }

        System.Assert(foundChangeHistory, 'Did not find history record for change');
    }    

    @isTest
    static void testInsertandUpdateNulls()
    {
        Risk__c risk = new Risk__c(
            Expected_Residual_or_Current_Impact__c=null,
            Expected_Residual_or_Current_Likelihood__c=null,
            Expected_Inherent_Impact__c=null,
            Expected_Inherent_Likelihood__c=null,
            Expected_Target_Impact__c=null,
            Expected_Target_Likelihood__c=null
            );

        insert risk;
        
        List<Risk_History__c> histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Likelihood_New__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Likelihood_New__c,

            Expected_Current_Impact_Old__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Impact_Old__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        // Check for history record for initial insert.
        System.AssertEquals(1, histories.size(), 'Expected 1 history record, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            System.Assert(history.Change_Description__c.containsIgnoreCase('initial'));
            System.AssertEquals(null, history.Expected_Current_Impact_New__c);
            System.AssertEquals(null, history.Expected_Current_Likelihood_New__c);
            System.AssertEquals(null, history.Expected_Inherent_Impact_New__c);
            System.AssertEquals(null, history.Expected_Inherent_Likelihood_New__c);
            System.AssertEquals(null, history.Expected_Target_Impact_New__c);
            System.AssertEquals(null, history.Expected_Target_Likelihood_New__c);

            System.AssertEquals(null, history.Expected_Current_Impact_Old__c);
            System.AssertEquals(null, history.Expected_Current_Likelihood_Old__c);
            System.AssertEquals(null, history.Expected_Inherent_Impact_Old__c);
            System.AssertEquals(null, history.Expected_Inherent_Likelihood_Old__c);
            System.AssertEquals(null, history.Expected_Target_Impact_Old__c);
            System.AssertEquals(null, history.Expected_Target_Likelihood_Old__c);
        }

        risk.Expected_Residual_or_Current_Impact__c = '5';
        risk.Expected_Residual_or_Current_Likelihood__c = '5';
        risk.Expected_Inherent_Impact__c = '5';
        risk.Expected_Inherent_Likelihood__c = '5';
        risk.Expected_Target_Impact__c = '5';
        risk.Expected_Target_Likelihood__c = '5';

        update risk;

        histories = [
            select
            Expected_Current_Impact_New__c,
            Expected_Current_Impact_Old__c,
            Expected_Inherent_Impact_New__c,
            Expected_Inherent_Impact_Old__c,
            Expected_Target_Impact_New__c,
            Expected_Target_Impact_Old__c,
            Expected_Current_Likelihood_New__c,
            Expected_Current_Likelihood_Old__c,
            Expected_Inherent_Likelihood_New__c,
            Expected_Inherent_Likelihood_Old__c,
            Expected_Target_Likelihood_New__c,
            Expected_Target_Likelihood_Old__c,
            Change_Description__c
            from Risk_History__c
            where Risk__c = :risk.Id
            ];

        Boolean foundChangeHistory = false;

        // Check for history record for updated values.
        System.AssertEquals(2, histories.size(), 'Expected 2 history records, found ' + histories.size());
        for (Risk_History__c history : histories)
        {
            if (history.Change_Description__c.containsIgnoreCase('change'))
            {
                System.AssertEquals(5, history.Expected_Current_Impact_New__c);
                System.AssertEquals(0, history.Expected_Current_Impact_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Impact_New__c);
                System.AssertEquals(0, history.Expected_Inherent_Impact_Old__c);
                System.AssertEquals(5, history.Expected_Target_Impact_New__c);
                System.AssertEquals(0, history.Expected_Target_Impact_Old__c);

                System.AssertEquals(5, history.Expected_Current_Likelihood_New__c);
                System.AssertEquals(0, history.Expected_Current_Likelihood_Old__c);
                System.AssertEquals(5, history.Expected_Inherent_Likelihood_New__c);
                System.AssertEquals(0, history.Expected_Inherent_Likelihood_Old__c);
                System.AssertEquals(5, history.Expected_Target_Likelihood_New__c);
                System.AssertEquals(0, history.Expected_Target_Likelihood_Old__c);

                foundChangeHistory = true;
            }
        }

        System.Assert(foundChangeHistory, 'Did not find history record for change');
    }    
}