src/objects/UGI_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Quarterly_Review_Status_Track__c</fullName>
        <label>Quarterly Review Status Track</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quarterly_Review_Status__c</fullName>
        <label>Quarterly Review Status</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed but no changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed with changes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>UGI Risk</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UGI Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateQuaterlyReviewStatusUGI.cls
public class UpdateQuaterlyReviewStatusUGI {
    String status;
    String riskId;
    public UpdateQuaterlyReviewStatusUGI(){
        riskId = ApexPages.currentPage().getParameters().get('id');
        status= ApexPages.currentPage().getParameters().get('status');        
    }
     public PageReference updateStatus(){ 
         if(riskId != null && status != null){
            UGI_Risk__c risk = [SELECT Id,Quarterly_Review_Status__c,Quarterly_Review_Status_Track__c FROM UGI_Risk__c WHERE Id=:riskId];
            risk.Quarterly_Review_Status__c = status;
            risk.Quarterly_Review_Status_Track__c = status + ' '+system.now().format('MM/dd/yyyy HH:mm:ss');
            update risk;
            return new PageReference('/'+riskId);
         }
         return null;
     }
}