src/objects/UGI_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Risk_Source__c</fullName>
        <label>Risk Source</label>
        <picklist>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>UGI Risk</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UGI Risks</pluralLabel>
    <recordTypes>
        <fullName>IA</fullName>
        <active>true</active>
        <label>IA</label>
    </recordTypes>
    <recordTypes>
        <fullName>SERC</fullName>
        <active>true</active>
        <label>SERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>SOX</fullName>
        <active>true</active>
        <label>SOX</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OverrideUGIRisk.cls
public class OverrideUGIRisk {
    public UGI_Risk__c risk{get;set;}
    public string riskSource{get;set;}
    
    string retURL;
    public OverrideUGIRisk(ApexPages.standardController std){
        for(UGI_Risk__c r : [select Risk_Source__c from UGI_Risk__c where id =: std.getRecord().Id]){
            riskSource = r.Risk_Source__c;
        }
        
        risk = (UGI_Risk__c)std.getRecord();
        retURL = apexPages.currentPage().getParameters().get('retURL');
    }
    
    public list<riskHistoryWrapper> getRiskHistories(){
        list<riskHistoryWrapper> rHistoryList = new list<riskHistoryWrapper>();
        if(risk != null && risk.Id != null){
            for(UGI_Risk__History h : [Select CreatedDate, CreatedBy.Name, CreatedBy.Id, Field, NewValue, OldValue from UGI_Risk__History where ParentId =: risk.Id order by CreatedDate Desc]){
                rHistoryList.add(new riskHistoryWrapper(h));
            }
        }
        return rHistoryList;
    }
    
    public List<Schema.FieldSetMember> getIAFields() {
        return SObjectType.UGI_Risk__c.FieldSets.IA.getFields();
    }
    
    public List<Schema.FieldSetMember> getSOX_UGI_Energy_ServicesFields() {
        return SObjectType.UGI_Risk__c.FieldSets.SOX_UGI_Energy_Services.getFields();
    }
    
    public List<Schema.FieldSetMember> getAssessmentFields() {
        return SObjectType.UGI_Risk__c.FieldSets.Assessment.getFields();
    }
    
    public List<Schema.FieldSetMember> getSOXAmeriGasPartnersFields() {
        return SObjectType.UGI_Risk__c.FieldSets.SOX.getFields();
    }
    
    
    public List<Schema.FieldSetMember> getSERCFields() {
        return SObjectType.UGI_Risk__c.FieldSets.SERC.getFields();
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference(retURL);
        return pg;
    }
    
    public class riskHistoryWrapper{
        public UGI_Risk__History riskHistory{get;set;}
        public string action{get;set;}
        public riskHistoryWrapper(UGI_Risk__History riskHistory){
            this.riskHistory = riskHistory;
            if(riskHistory.Field == 'created'){
                action = 'Created';
            }else{
                action = 'Changed '+riskHistory.Field.removeEnd('__c');
            }
        }
    }
}